import type { AppLayoutDmAndShellSession } from './useAppLayoutDmAndShellSession';
import type { AppLayoutDmAndShellRolesTree } from './useAppLayoutDmAndShellRolesTree';
import type { AppLayoutDmAndShellEchoDm } from './useAppLayoutDmAndShellEchoDm';
import type { AppLayoutDmAndShellNavVoice } from './useAppLayoutDmAndShellNavVoice';

type Parts = {
  session: AppLayoutDmAndShellSession;
  roles: AppLayoutDmAndShellRolesTree;
  echoDm: AppLayoutDmAndShellEchoDm;
  navVoice: AppLayoutDmAndShellNavVoice;
};

function pickSessionSlice(p: Parts) {
  const s = p.session;
  return {
    actionRailTopLayout: s.actionRailTopLayout,
    actionRegistryRef: s.actionRegistryRef,
    authSession: s.authSession,
    authStateGeneration: s.authStateGeneration,
    channelAttentionByChannelId: s.channelAttentionByChannelId,
    channelIconResolver: s.channelIconResolver,
    chatMessageNavBridge: s.chatMessageNavBridge,
    compactGuildTriPaneChannelPanelOpen: s.compactGuildTriPaneChannelPanelOpen,
    compactPagerPane: s.compactPagerPane,
    isCompactPhoneShell: s.isCompactPhoneShell,
    mobileBottomTab: s.mobileBottomTab,
    mobileChannelSheetOpen: s.mobileChannelSheetOpen,
    mobileHomeStack: s.mobileHomeStack,
    mobileMembersOverlayOpen: s.mobileMembersOverlayOpen,
    mobileServersStack: s.mobileServersStack,
    devModeIdsEnabled: s.devModeIdsEnabled,
    devSettings: s.devSettings,
    discordOnlineByUserId: s.discordOnlineByUserId,
    dmAttentionByChannelId: s.dmAttentionByChannelId,
    echoAttention: s.echoAttention,
    echoSession: s.echoSession,
    friendshipQueries: s.friendshipQueries,
    guildMobileVcLobby: s.guildMobileVcLobby,
    inviteLandingActiveComputed: s.inviteLandingActiveComputed,
    inviteLandingActiveRef: s.inviteLandingActiveRef,
    isCompactGuildSplitShell: s.isCompactGuildSplitShell,
    isCompactShell: s.isCompactShell,
    isDmUiContext: s.isDmUiContext,
    lastOnlineAtByUserId: s.lastOnlineAtByUserId,
    layoutDims: s.layoutDims,
    linkedDiscordState: s.linkedDiscordState,
    linkedDiscordUserId: s.linkedDiscordUserId,
    navTraceId: s.navTraceId,
    openGuestUpgradeForDmRef: s.openGuestUpgradeForDmRef,
    platform: s.platform,
    presenceByUserId: s.presenceByUserId,
    presenceMobileByUserId: s.presenceMobileByUserId,
    readStateByChannelId: s.readStateByChannelId,
    sealWithGroupDmAndNavigation: s.sealWithGroupDmAndNavigation,
    selectServerViaStore: s.selectServerViaStore,
    selectedServerIdRef: s.selectedServerIdRef,
    selectedServerRef: s.selectedServerRef,
    serverAttentionByServerId: s.serverAttentionByServerId,
    serverNotificationLevelByServerId: s.serverNotificationLevelByServerId,
    serverRowsRef: s.serverRowsRef,
    serverStore: s.serverStore,
    sessionEndedMessage: s.sessionEndedMessage,
    showApiFetchErrorBanner: s.showApiFetchErrorBanner,
    themeStore: s.themeStore,
    uiState: s.uiState,
    wireMessageGoToMessage: s.wireMessageGoToMessage,
    workspace: s.workspace,
    workspaceMembersByServer: s.workspaceMembersByServer,
  };
}

function pickLayoutSlice(p: Parts) {
  const l = p.session.layoutDims;
  return {
    beginVcActivitySessionChannelLayout: l.beginVcActivitySessionChannelLayout,
    bumpVoiceMobileChatFromCallScrollDown:
      l.bumpVoiceMobileChatFromCallScrollDown,
    bumpVoiceMobileChatFromCallScrollUp: l.bumpVoiceMobileChatFromCallScrollUp,
    channelPanelBubbleMode: l.channelPanelBubbleMode,
    channelPanelCollapsed: l.channelPanelCollapsed,
    channelPanelWidth: l.channelPanelWidth,
    endVcActivitySessionChannelLayout: l.endVcActivitySessionChannelLayout,
    expandVoiceSideChat: l.expandVoiceSideChat,
    mainContentColumns: l.mainContentColumns,
    markMemberPanelCollapsedByUser: l.markMemberPanelCollapsedByUser,
    markMemberPanelExpandedByUser: l.markMemberPanelExpandedByUser,
    memberListShowGuests: l.memberListShowGuests,
    memberPanelAutoCollapseUserOverride: l.memberPanelAutoCollapseUserOverride,
    memberPanelCollapsed: l.memberPanelCollapsed,
    memberPanelWidth: l.memberPanelWidth,
    narrowChannelPanelForActivityOverflowStep:
      l.narrowChannelPanelForActivityOverflowStep,
    resetChannelWidth: l.resetChannelWidth,
    resetMemberWidth: l.resetMemberWidth,
    resetVoiceSideChatWidth: l.resetVoiceSideChatWidth,
    startChannelResize: l.startChannelResize,
    startMemberResize: l.startMemberResize,
    startVoiceSideChatResize: l.startVoiceSideChatResize,
    toggleChannelPanelBubbleMode: l.toggleChannelPanelBubbleMode,
    toggleVoiceSideChat: l.toggleVoiceSideChat,
    voiceMobileSheetLevel: l.voiceMobileSheetLevel,
    voiceSideChatCollapsed: l.voiceSideChatCollapsed,
    voiceSideChatWidth: l.voiceSideChatWidth,
  };
}

function pickUiStateChromeSlice(p: Parts) {
  const u = p.session.uiState;
  return {
    activeGroupSettingsId: u.activeGroupSettingsId,
    activeMemberProfile: u.activeMemberProfile,
    activeRailTab: u.activeRailTab,
    activeChannelId: u.activeChannelId,
    addServerInitialView: u.addServerInitialView,
    addVcYoutubeToQueue: u.addVcYoutubeToQueue,
    applyVcDeafened: u.applyVcDeafened,
    applyVcMuted: u.applyVcMuted,
    applyVcYoutubeWatchTogetherRemote: u.applyVcYoutubeWatchTogetherRemote,
    applyVcWatchTogetherRemote: u.applyVcWatchTogetherRemote,
    authModalInitialLoginEntry: u.authModalInitialLoginEntry,
    authModalInitialSubView: u.authModalInitialSubView,
    authModalInitialTab: u.authModalInitialTab,
    authModalPasskeyOnOpen: u.authModalPasskeyOnOpen,
    closeVcActivity: u.closeVcActivity,
    currentVoiceChannelId: u.currentVoiceChannelId,
    currentVoiceChannelName: u.currentVoiceChannelName,
    customStatus: u.customStatus,
    desktopStreamingControlMode: u.desktopStreamingControlMode,
    dmActiveTab: u.dmActiveTab,
    dmPanelWidth: u.dmPanelWidth,
    expandedProfile: u.expandedProfile,
    expandedProfileTargetUserId: u.expandedProfileTargetUserId,
    fullscreenStreamParticipantId: u.fullscreenStreamParticipantId,
    groupDMLockedIds: u.groupDMLockedIds,
    groupDMPreselectedIds: u.groupDMPreselectedIds,
    groupDMs: u.groupDMs,
    groupDmSettingsInitialFocus: u.groupDmSettingsInitialFocus,
    inviteModalVoiceChannelId: u.inviteModalVoiceChannelId,
    inviteModalVoiceChannelName: u.inviteModalVoiceChannelName,
    isAddServerModalOpen: u.isAddServerModalOpen,
    isAuthModalOpen: u.isAuthModalOpen,
    isDMPanelOpen: u.isDMPanelOpen,
    isDesktopStreamingControlOpen: u.isDesktopStreamingControlOpen,
    isExpandedProfileModalOpen: u.isExpandedProfileModalOpen,
    isExpandedProfileSidePanel: u.isExpandedProfileSidePanel,
    isGroupDMModalOpen: u.isGroupDMModalOpen,
    isGroupDMSettingsOpen: u.isGroupDMSettingsOpen,
    isGroupOverviewOpen: u.isGroupOverviewOpen,
    isInviteModalOpen: u.isInviteModalOpen,
    isMemberPopoutOpen: u.isMemberPopoutOpen,
    isMoreServersCompact: u.isMoreServersCompact,
    isMoreServersPanelOpen: u.isMoreServersPanelOpen,
    isMoreServersPinned: u.isMoreServersPinned,
    isScreenSharePickerOpen: u.isScreenSharePickerOpen,
    isSelfProfilePopoutOpen: u.isSelfProfilePopoutOpen,
    isServerSettingsModalOpen: u.isServerSettingsModalOpen,
    isSettingsModalOpen: u.isSettingsModalOpen,
    isSystemSettingsOpen: u.isSystemSettingsOpen,
    memberPopoutAnchor: u.memberPopoutAnchor,
    memberPopoutOpenRolesPanel: u.memberPopoutOpenRolesPanel,
  };
}

function pickUiStateVoiceSlice(p: Parts) {
  const u = p.session.uiState;
  return {
    micTestListenDeafenActive: u.micTestListenDeafenActive,
    moveVcYoutubeInQueue: u.moveVcYoutubeInQueue,
    onJoinVoice: u.onJoinVoice,
    onLeaveVoice: u.onLeaveVoice,
    openAuthModal: u.openAuthModal,
    openUserSettingsToDiscordFromAddServer:
      u.openUserSettingsToDiscordFromAddServer,
    openVcActivityClusterRush: u.openVcActivityClusterRush,
    openVcActivityCodenames: u.openVcActivityCodenames,
    openVcActivityGarticPhone: u.openVcActivityGarticPhone,
    openVcActivityGooberDash: u.openVcActivityGooberDash,
    openVcActivityHangman: u.openVcActivityHangman,
    openVcActivityKrunker: u.openVcActivityKrunker,
    openVcActivityOpenGuessr: u.openVcActivityOpenGuessr,
    openVcActivityPicker: u.openVcActivityPicker,
    openVcActivityRichup: u.openVcActivityRichup,
    openVcActivitySkribblIo: u.openVcActivitySkribblIo,
    openVcActivitySkriggles: u.openVcActivitySkriggles,
    openVcActivitySmashKarts: u.openVcActivitySmashKarts,
    openVcActivityTicTacToe: u.openVcActivityTicTacToe,
    openVcActivityWordle: u.openVcActivityWordle,
    openVcActivityYoutubeBrowse: u.openVcActivityYoutubeBrowse,
    openVcActivityWatchTogether: u.openVcActivityWatchTogether,
    patchWatchTogetherUi: u.patchWatchTogetherUi,
    playWatchTogetherAtIndex: u.playWatchTogetherAtIndex,
    pfpBarExpanded: u.pfpBarExpanded,
    playVcYoutubeAtIndex: u.playVcYoutubeAtIndex,
    playVcYoutubeNext: u.playVcYoutubeNext,
    playVcYoutubePrevious: u.playVcYoutubePrevious,
    profileNotes: u.profileNotes,
    removeVcYoutubeFromQueue: u.removeVcYoutubeFromQueue,
    resetDmPanelWidth: u.resetDmPanelWidth,
    selectedDMUserId: u.selectedDMUserId,
    selectedMessageRequestId: u.selectedMessageRequestId,
    selfProfileAnchor: u.selfProfileAnchor,
    serverSettingsModalActiveSection: u.serverSettingsModalActiveSection,
    serverSettingsModalInitialSection: u.serverSettingsModalInitialSection,
    setMicTestListenDeafen: u.setMicTestListenDeafen,
    setVcActivityYoutubeVideo: u.setVcActivityYoutubeVideo,
    setVcYoutubeBrowseOpen: u.setVcYoutubeBrowseOpen,
    setWatchTogetherBrowseOpen: u.setWatchTogetherBrowseOpen,
    setWatchTogetherLobbyRole: u.setWatchTogetherLobbyRole,
    startWatchTogetherSession: u.startWatchTogetherSession,
    ensureWatchTogetherSessionId: u.ensureWatchTogetherSessionId,
    settingsModalActiveSection: u.settingsModalActiveSection,
    settingsModalInitialSection: u.settingsModalInitialSection,
    startDmPanelResize: u.startDmPanelResize,
    toggleMoreServersPanelChrome: u.toggleMoreServersPanel,
    vcActivityUi: u.vcActivityUi,
    vcDeafened: u.vcDeafened,
    vcMuted: u.vcMuted,
    vcScreenshare: u.vcScreenshare,
    vcVideo: u.vcVideo,
  };
}

function pickRolesSlice(p: Parts) {
  const r = p.roles;
  const inv = r.selectedServerInvite;
  return {
    categoriesForServer: r.categoriesForServer,
    channelTree: r.channelTree,
    createDirectHexInvite: inv.createDirectHexInvite,
    currentUser: r.currentUser,
    currentUserComputed: r.currentUserComputed,
    currentUserIdForSocket: r.currentUserIdForSocket,
    directHexInviteBusy: inv.directHexInviteBusy,
    directHexInviteLink: inv.directHexInviteLink,
    echoCanContext: r.echoCanContext,
    findChannelContextById: r.findChannelContextById,
    getFirstTextChannelId: r.getFirstTextChannelId,
    getServerChannelInfoForMainSurface: r.getServerChannelInfoForMainSurface,
    groupDmMaxMembers: r.groupDmMaxMembers,
    immediateShellSwitchPending: r.immediateShellSwitchPending,
    inviteApplicationsEnabled: r.inviteApplicationsEnabled,
    inviteCanCreateDirectHexInvite: r.inviteCanCreateDirectHexInvite,
    inviteJoinLinksEnabled: r.inviteJoinLinksEnabled,
    inviteLinkForServer: inv.inviteLinkForServer,
    inviteLinkFromApi: inv.inviteLinkFromApi,
    inviteLinkFromSelectedServer: inv.inviteLinkFromSelectedServer,
    inviteLinkLookupPending: inv.inviteLinkLookupPending,
    isAuthenticatedComputed: r.isAuthenticatedComputed,
    isChannelActive: r.isChannelActive,
    isGuestComputed: r.isGuestComputed,
    isGuildShellSettledForSwitchPending: r.isGuildShellSettledForSwitchPending,
    newlyCreatedServerId: inv.newlyCreatedServerId,
    rawCategoriesForServer: r.rawCategoriesForServer,
    resolveMemberHighestRole: r.resolveMemberHighestRole,
    resolvePreviewChannelPermission: r.resolvePreviewChannelPermission,
    rolePreviewState: r.rolePreviewState,
    roleUi: r.roleUi,
    selectedServerEcho: r.selectedServerEcho,
    selectedServerInvite: r.selectedServerInvite,
    selectedServerView: r.selectedServerView,
    selfProfile: r.selfProfile,
    syncVanityAcrossServerLists: inv.syncVanityAcrossServerLists,
    watchActiveChannelWithServerChange: r.watchActiveChannelWithServerChange,
  };
}

function pickEchoDmSlice(p: Parts) {
  const e = p.echoDm;
  return {
    _isOpeningDmThread: e._isOpeningDmThread,
    activeChannelContext: e.activeChannelContext,
    applyVcYoutubeWatchTogetherRemoteOnVoice:
      e.applyVcYoutubeWatchTogetherRemoteOnVoice,
    applyVcWatchTogetherRemoteOnVoice: e.applyVcWatchTogetherRemoteOnVoice,
    dmCallWithUserIdForShellLog: e.dmCallWithUserIdForShellLog,
    echoBlockedUserIds: e.echoBlockedUserIds,
    echoDmActiveCallParticipantUserIdsByChannelId:
      e.echoDmActiveCallParticipantUserIdsByChannelId,
    echoDmLastActivityAtMsByChannelId: e.echoDmLastActivityAtMsByChannelId,
    echoDmLastActivityIdByChannelId: e.echoDmLastActivityIdByChannelId,
    echoDmPeerByChannelId: e.echoDmPeerByChannelId,
    echoDmState: e.echoDmState,
    echoDmThreadIds: e.echoDmThreadIds,
    effectiveActiveChannel: e.effectiveActiveChannel,
    favoriteDmInboxStore: e.favoriteDmInboxStore,
    getLatestDmInboxTargetForRailRef: e.getLatestDmInboxTargetForRailRef,
    getLatestDmPeerUserIdForRail: e.getLatestDmPeerUserIdForRail,
    handleActiveChannelChangeNavigation: e.handleActiveChannelChangeNavigation,
    hiddenDmInboxStore: e.hiddenDmInboxStore,
    isEchoUserBlocked: e.isEchoUserBlocked,
    isKnownDmChannelId: e.isKnownDmChannelId,
    isPersistedEchoDmThread: e.isPersistedEchoDmThread,
    isViewingVoiceChannel: e.isViewingVoiceChannel,
    leaveDmUiIfViewingUser: e.leaveDmUiIfViewingUser,
    mergeEchoBlockedFromApi: e.mergeEchoBlockedFromApi,
    mergeEchoDmThread: e.mergeEchoDmThread,
    mergeEchoDmThreadFromRealtime: e.mergeEchoDmThreadFromRealtime,
    mergeEchoDmThreadsFromApi: e.mergeEchoDmThreadsFromApi,
    navigateToDmForAnswerRef: e.navigateToDmForAnswerRef,
    onSelectDmUser: e.onSelectDmUser,
    openVcActivityClusterRushOnVoice: e.openVcActivityClusterRushOnVoice,
    openVcActivityCodenamesOnVoice: e.openVcActivityCodenamesOnVoice,
    openVcActivityGarticPhoneOnVoice: e.openVcActivityGarticPhoneOnVoice,
    openVcActivityGooberDashOnVoice: e.openVcActivityGooberDashOnVoice,
    openVcActivityHangmanOnVoice: e.openVcActivityHangmanOnVoice,
    openVcActivityKrunkerOnVoice: e.openVcActivityKrunkerOnVoice,
    openVcActivityOpenGuessrOnVoice: e.openVcActivityOpenGuessrOnVoice,
    openVcActivityPickerOnVoice: e.openVcActivityPickerOnVoice,
    openVcActivityRichupOnVoice: e.openVcActivityRichupOnVoice,
    openVcActivitySkribblIoOnVoice: e.openVcActivitySkribblIoOnVoice,
    openVcActivitySkrigglesOnVoice: e.openVcActivitySkrigglesOnVoice,
    openVcActivitySmashKartsOnVoice: e.openVcActivitySmashKartsOnVoice,
    openVcActivityTicTacToeOnVoice: e.openVcActivityTicTacToeOnVoice,
    openVcActivityWordleOnVoice: e.openVcActivityWordleOnVoice,
    openVcActivityYoutubeBrowseOnVoice: e.openVcActivityYoutubeBrowseOnVoice,
    openVcActivityWatchTogetherOnVoice: e.openVcActivityWatchTogetherOnVoice,
    selectDmUser: e.selectDmUser,
    selectGroupDmForIncomingRail: e.selectGroupDmForIncomingRail,
  };
}

function pickNavVoiceSlice(p: Parts) {
  const n = p.navVoice;
  return {
    callVoice: n.callVoice,
    closeDMPanel: n.closeDMPanel,
    clearPhoneHomeDmThread: n.clearPhoneHomeDmThread,
    closeGuildMobileVcLobby: n.closeGuildMobileVcLobby,
    dispatchNav: n.dispatchNav,
    hasGuildChannelChrome: n.hasGuildChannelChrome,
    isServerEmptyOnboarding: n.isServerEmptyOnboarding,
    mainSurface: n.mainSurface,
    openDmInboxFromRailOverflow: n.openDmInboxFromRailOverflow,
    openGuildMobileVcLobby: n.openGuildMobileVcLobby,
    openServerSettingsFromUrl: n.openServerSettingsFromUrl,
    openServerSurface: n.openServerSurface,
    selectDMTab: n.selectDMTab,
    selectExploreTab: n.selectExploreTab,
    selectIncomingDmFromRail: n.selectIncomingDmFromRail,
    selectIncomingGroupDmFromRail: n.selectIncomingGroupDmFromRail,
    selectServersRailOnly: n.selectServersRailOnly,
    selectServersTab: n.selectServersTab,
    shellNavState: n.shellNavState,
    suspiciousEmptyWorkspace: n.suspiciousEmptyWorkspace,
    voiceChannelForParticipants: n.voiceChannelForParticipants,
  };
}

export function buildWireAppLayoutDmAndShellResult(parts: Parts) {
  return {
    ...pickSessionSlice(parts),
    ...pickLayoutSlice(parts),
    ...pickUiStateChromeSlice(parts),
    ...pickUiStateVoiceSlice(parts),
    ...pickRolesSlice(parts),
    ...pickEchoDmSlice(parts),
    ...pickNavVoiceSlice(parts),
  };
}
