import type { AppLayoutControllerContext } from './appLayoutControllerTypes';

export function buildAppLayoutExpose(ctx: AppLayoutControllerContext) {
  const exposed: Record<string, unknown> = {
    appActionRegistry: ctx.appActionRegistry,
    appLayoutActions: ctx.appLayoutActions,
    chatMessageNavBridge: ctx.chatMessageNavBridge,
    DM_PANEL_WIDTH: ctx.DM_PANEL_WIDTH,
    ExploreView: ctx.ExploreView,
    MORE_SERVERS_COMPACT_WIDTH: ctx.MORE_SERVERS_COMPACT_WIDTH,
    MORE_SERVERS_PANEL_WIDTH: ctx.MORE_SERVERS_PANEL_WIDTH,
    acceptFriendRequest: ctx.acceptFriendRequest,
    activeChannel: ctx.activeChannel,
    activeChannelContext: ctx.activeChannelContext,
    activeChannelId: ctx.activeChannelId,
    activeChannelMessagesMap: ctx.activeChannelMessagesMap,
    linkedDiscordUserId: ctx.linkedDiscordUserId,
    linkedDiscordState: ctx.linkedDiscordState,
    activeGroupCallMembers: ctx.activeGroupCallMembers,
    activeGroupDM: ctx.activeGroupDM,
    activeGroupSettingsId: ctx.activeGroupSettingsId,
    activeMemberNote: ctx.activeMemberNote,
    activeMemberProfile: ctx.activeMemberProfile,
    activeRailTab: ctx.activeRailTab,
    activeVoiceChannelParticipants: ctx.activeVoiceChannelParticipants,
    getVcActivityPresenceForUser: ctx.getVcActivityPresenceForUser,
    getVcChannelActivityPresenceForChannel:
      ctx.getVcChannelActivityPresenceForChannel,
    effectiveVcActivityKingUserId: ctx.effectiveVcActivityKingUserId,
    vcHangmanActivity: ctx.vcHangmanActivity,
    hangmanRosterUserIds: ctx.hangmanRosterUserIds,
    hangmanGameRoomConnected: ctx.hangmanGameRoomConnected,
    hangmanGameRoomLastError: ctx.hangmanGameRoomLastError,
    commitVcHangmanWord: ctx.commitVcHangmanWord,
    requestVcHangmanGuessLetter: ctx.requestVcHangmanGuessLetter,
    requestVcHangmanNextRound: ctx.requestVcHangmanNextRound,
    wordlineView: ctx.wordlineView,
    submitWordlineGuess: ctx.submitWordlineGuess,
    setWordlineMode: ctx.setWordlineMode,
    vcSkrigglesActivity: ctx.vcSkrigglesActivity,
    skrigglesRosterUserIds: ctx.skrigglesRosterUserIds,
    skrigglesCanvasEvents: ctx.skrigglesCanvasEvents,
    commitSkrigglesWordChoice: ctx.commitSkrigglesWordChoice,
    submitSkrigglesGuess: ctx.submitSkrigglesGuess,
    updateSkrigglesSettings: ctx.updateSkrigglesSettings,
    startSkrigglesGame: ctx.startSkrigglesGame,
    advanceSkrigglesRound: ctx.advanceSkrigglesRound,
    publishSkrigglesStrokeBatch: ctx.publishSkrigglesStrokeBatch,
    publishSkrigglesCanvasCmd: ctx.publishSkrigglesCanvasCmd,
    publishSkrigglesCanvasSnapshot: ctx.publishSkrigglesCanvasSnapshot,
    tickSkrigglesTimers: ctx.tickSkrigglesTimers,
    vcTicTacToeActivity: ctx.vcTicTacToeActivity,
    vcTicTacToePendingInvite: ctx.vcTicTacToePendingInvite,
    sendVcTicTacToeChallenge: ctx.sendVcTicTacToeChallenge,
    respondVcTicTacToeInvite: ctx.respondVcTicTacToeInvite,
    dismissVcTicTacToeInvite: ctx.dismissVcTicTacToeInvite,
    requestVcTicTacToeMove: ctx.requestVcTicTacToeMove,
    requestVcTicTacToeRematch: ctx.requestVcTicTacToeRematch,
    vcCodenamesActivity: ctx.vcCodenamesActivity,
    codenamesRosterUserIds: ctx.codenamesRosterUserIds,
    vcCodenamesSpymasterKey: ctx.vcCodenamesSpymasterKey,
    commitVcCodenamesDeal: ctx.commitVcCodenamesDeal,
    requestVcCodenamesSetup: ctx.requestVcCodenamesSetup,
    requestVcCodenamesClue: ctx.requestVcCodenamesClue,
    requestVcCodenamesReveal: ctx.requestVcCodenamesReveal,
    requestVcCodenamesEndTurn: ctx.requestVcCodenamesEndTurn,
    requestVcCodenamesNewGame: ctx.requestVcCodenamesNewGame,
    requestVcCodenamesPushKeyToOrchestrator:
      ctx.requestVcCodenamesPushKeyToOrchestrator,
    liveKitState: ctx.liveKitState,
    liveKitNetworkStats: ctx.liveKitNetworkStats,
    liveKitRoom: ctx.liveKitRoom,
    speakingMap: ctx.speakingMap,
    localSpeaking: ctx.localSpeaking,
    localAudioLevel: ctx.localAudioLevel,
    switchMicDevice: ctx.switchMicDevice,
    switchSpeakerDevice: ctx.switchSpeakerDevice,
    setLkOutputVolume: ctx.setLkOutputVolume,
    reapplyVoiceProcessing: ctx.reapplyVoiceProcessing,
    setMicTestListenDeafen: ctx.setMicTestListenDeafen,
    vcRemoteParticipants: ctx.vcRemoteParticipants,
    vcMirrorCamera: ctx.vcMirrorCamera,
    switchVcCamera: ctx.switchVcCamera,
    setVcVideoQuality: ctx.setVcVideoQuality,
    addFilter: ctx.addFilter,
    addServerInitialView: ctx.addServerInitialView,
    addServerJoinError: ctx.addServerJoinError,
    addServerCreateBusy: ctx.addServerCreateBusy,
    addServerJoinBusy: ctx.addServerJoinBusy,
    addServerJoinInvitePrefill: ctx.addServerJoinInvitePrefill,
    exploreDirectoryJoinBusy: ctx.exploreDirectoryJoinBusy,
    allChannels: ctx.allChannels,
    appGridTemplateColumns: ctx.appGridTemplateColumns,
    applyEchoPresenceFromSocket: ctx.applyEchoPresenceFromSocket,
    authSession: ctx.authSession,
    callOverlay: ctx.callOverlay,
    canCreateChannels: ctx.canCreateChannels,
    canManageThisChannel: ctx.canManageThisChannel,
    canDeleteCurrentServer: ctx.canDeleteCurrentServer,
    canInviteToCurrentServer: ctx.canInviteToCurrentServer,
    canJoinPreviewVoiceChannel: ctx.canJoinPreviewVoiceChannel,
    canModerateMemberInServer: ctx.canModerateMemberInServer,
    canVcModerateMember: ctx.canVcModerateMember,
    canModerateMemberActionInServer: ctx.canModerateMemberActionInServer,
    canChangeMemberNicknameInServer: ctx.canChangeMemberNicknameInServer,
    canModerateMessageAuthor: ctx.canModerateMessageAuthor,
    canOpenInviteForServer: ctx.canOpenInviteForServer,
    canOpenServerSettings: ctx.canOpenServerSettings,
    canOpenServerSettingsForServer: ctx.canOpenServerSettingsForServer,
    cancelFriendRequest: ctx.cancelFriendRequest,
    categoriesForServer: ctx.categoriesForServer,
    categorySettingsTarget: ctx.categorySettingsTarget,
    categorySettingsEchoPermissionEditor:
      ctx.categorySettingsEchoPermissionEditor,
    channelPanelCollapsed: ctx.channelPanelCollapsed,
    channelPanelBubbleMode: ctx.channelPanelBubbleMode,
    channelPanelWidth: ctx.channelPanelWidth,
    toggleChannelPanelBubbleMode: ctx.toggleChannelPanelBubbleMode,
    channelSettingsCategoryPermissionDefaults:
      ctx.channelSettingsCategoryPermissionDefaults,
    channelSettingsCategoryAutoDeleteAfterSeconds:
      ctx.channelSettingsCategoryAutoDeleteAfterSeconds,
    channelSettingsEchoPermissionEditor:
      ctx.channelSettingsEchoPermissionEditor,
    channelSettingsTarget: ctx.channelSettingsTarget,
    clearRolePreview: ctx.clearRolePreview,
    clearSearch: ctx.clearSearch,
    closeDMPanel: ctx.closeDMPanel,
    clearPhoneHomeDmThread: ctx.clearPhoneHomeDmThread,
    closePinsDropdown: ctx.closePinsDropdown,
    createChannelCategoryNames: ctx.createChannelCategoryNames,
    createChannelCategoryOptions: ctx.createChannelCategoryOptions,
    createChannelInitialCategoryId: ctx.createChannelInitialCategoryId,
    currentServerNotificationLevel: ctx.currentServerNotificationLevel,
    currentUser: ctx.currentUser,
    currentVoiceChannelId: ctx.currentVoiceChannelId,
    currentVoiceChannelName: ctx.currentVoiceChannelName,
    channelPanelVoiceChannelId: ctx.channelPanelVoiceChannelId,
    channelPanelVoiceChannelName: ctx.channelPanelVoiceChannelName,
    channelPanelVcMutedEffective: ctx.channelPanelVcMutedEffective,
    channelPanelVcDeafenedEffective: ctx.channelPanelVcDeafenedEffective,
    channelPanelVcVideoEffective: ctx.channelPanelVcVideoEffective,
    channelPanelVcScreenshareEffective: ctx.channelPanelVcScreenshareEffective,
    onChannelPanelVcMuted: ctx.onChannelPanelVcMuted,
    onChannelPanelVcDeafened: ctx.onChannelPanelVcDeafened,
    onChannelPanelVcVideo: ctx.onChannelPanelVcVideo,
    onChannelPanelVcScreenshare: ctx.onChannelPanelVcScreenshare,
    customStatus: ctx.customStatus,
    declineFriendRequest: ctx.declineFriendRequest,
    deleteMessage: ctx.deleteMessage,
    deleteMessageCore: ctx.deleteMessageCore,
    dmActiveTab: ctx.dmActiveTab,
    dmIncomingRailCluster: ctx.dmIncomingRailCluster,
    dmCallDeafened: ctx.dmCallDeafened,
    applyDmCallDeafened: ctx.applyDmCallDeafened,
    toggleDmCallMuted: ctx.toggleDmCallMuted,
    dmCallFullscreen: ctx.dmCallFullscreen,
    dmCallMuted: ctx.dmCallMuted,
    dmCallQuarterView: ctx.dmCallQuarterView,
    dmCallMatchesActiveChannel: ctx.dmCallMatchesActiveChannel,
    activeDmThreadCallUi: ctx.activeDmThreadCallUi,
    dmCallVideo: ctx.dmCallVideo,
    dmCallScreenshare: ctx.dmCallScreenshare,
    dmCallCallViewParticipants: ctx.dmCallCallViewParticipants,
    dmCallWithUserId: ctx.dmCallWithUserId,
    dmCallRinging: ctx.dmCallRinging,
    dmCallAwaitingAccept: ctx.dmCallAwaitingAccept,
    dmCallRingUi: ctx.dmCallRingUi,
    dmCallLobbyAfterSelfLeave: ctx.dmCallLobbyAfterSelfLeave,
    dmCallIncoming: ctx.dmCallIncoming,
    dmCallRingRemoteVanishing: ctx.dmCallRingRemoteVanishing,
    dmCallGlassPeer: ctx.dmCallGlassPeer,
    dmCallVoiceStripThreadId: ctx.dmCallVoiceStripThreadId,
    dmCallVoiceStripTitle: ctx.dmCallVoiceStripTitle,
    onGuildChannelVcMuted: ctx.onGuildChannelVcMuted,
    onGuildChannelVcDeafened: ctx.onGuildChannelVcDeafened,
    onGuildChannelVcVideo: ctx.onGuildChannelVcVideo,
    onGuildChannelVcScreenshare: ctx.onGuildChannelVcScreenshare,
    onDmCallVcMuted: ctx.onDmCallVcMuted,
    onDmCallVcDeafened: ctx.onDmCallVcDeafened,
    onDmCallVcVideo: ctx.onDmCallVcVideo,
    onDmCallVcScreenshare: ctx.onDmCallVcScreenshare,
    dmGroupFriends: ctx.dmGroupFriends,
    dmPanelWidth: ctx.dmPanelWidth,
    dmPartnerUser: ctx.dmPartnerUser,
    presenceByUserId: ctx.presenceByUserId,
    dmInboxEntriesForPanel: ctx.dmInboxEntriesForPanel,
    echoDmPeerByChannelId: ctx.echoDmPeerByChannelId,
    dmUsersForDmPanel: ctx.dmUsersForDmPanel,
    echoCanBanMembers: ctx.echoCanBanMembers,
    echoCanChangeNicknames: ctx.echoCanChangeNicknames,
    echoCanCreateChannel: ctx.echoCanCreateChannel,
    echoCanCreateInvite: ctx.echoCanCreateInvite,
    echoCanKickMembers: ctx.echoCanKickMembers,
    echoCanManageMessages: ctx.echoCanManageMessages,
    echoCanManageNicknames: ctx.echoCanManageNicknames,
    echoCanModerateMembers: ctx.echoCanModerateMembers,
    echoCanTimeoutMembers: ctx.echoCanTimeoutMembers,
    echoCapabilitiesForServerId: ctx.echoCapabilitiesForServerId,
    isEchoRoleBootstrapLoading: ctx.isEchoRoleBootstrapLoading,
    liveChannelCapabilities: ctx.liveChannelCapabilities,
    echoChannelHistory: ctx.echoChannelHistory,
    echoRoleCatalog: ctx.echoRoleCatalog,
    echoWorkspaceError: ctx.echoWorkspaceError,
    editMessage: ctx.editMessage,
    effectiveActiveChannel: ctx.effectiveActiveChannel,
    endDmCall: ctx.endDmCall,
    leaveDmCallVoice: ctx.leaveDmCallVoice,
    rejoinDmCallVoice: ctx.rejoinDmCallVoice,
    answerDmCall: ctx.answerDmCall,
    declineDmCall: ctx.declineDmCall,
    compactPagerPane: ctx.compactPagerPane,
    compactGuildTriPaneChannelPanelOpen:
      ctx.compactGuildTriPaneChannelPanelOpen,
    guildMobileVcLobby: ctx.guildMobileVcLobby,
    openGuildMobileVcLobby: ctx.openGuildMobileVcLobby,
    closeGuildMobileVcLobby: ctx.closeGuildMobileVcLobby,
    expandChannels: ctx.expandChannels,
    collapseMembers: ctx.collapseMembers,
    expandMembers: ctx.expandMembers,
    expandVoiceSideChat: ctx.expandVoiceSideChat,
    expandedProfile: ctx.expandedProfile,
    expandedProfileNote: ctx.expandedProfileNote,
    exploreDiscoverableServers: ctx.exploreDiscoverableServers,
    filterChips: ctx.filterChips,
    findChannelContextById: ctx.findChannelContextById,
    getChannelDisplayName: ctx.getChannelDisplayName,
    getChannelIcon: ctx.getChannelIcon,
    getFirstTextChannelId: ctx.getFirstTextChannelId,
    getLatestDMUserId: ctx.getLatestDMUserId,
    getServerChannelInfoForMainSurface: ctx.getServerChannelInfoForMainSurface,
    goToPinnedMessage: ctx.goToPinnedMessage,
    goToSearchPage: ctx.goToSearchPage,
    groupDMListForPanel: ctx.groupDMListForPanel,
    groupDMLockedIds: ctx.groupDMLockedIds,
    groupDMPreselectedIds: ctx.groupDMPreselectedIds,
    groupDmMaxMembers: ctx.groupDmMaxMembers,
    groupSettingsId: ctx.groupSettingsId,
    groupSettingsMembers: ctx.groupSettingsMembers,
    groupDMs: ctx.groupDMs,
    guestFriendsLocked: ctx.guestFriendsLocked,
    handleActiveChannelChange: ctx.handleActiveChannelChange,
    handleCallViewOpenProfile: ctx.handleCallViewOpenProfile,
    handleChangeMemberNicknameFromMemberList:
      ctx.handleChangeMemberNicknameFromMemberList,
    handleCategoryDelete: ctx.handleCategoryDelete,
    handleCategoryReorder: ctx.handleCategoryReorder,
    handleCategorySettingsSave: ctx.handleCategorySettingsSave,
    handleChannelDelete: ctx.handleChannelDelete,
    handleChannelReorder: ctx.handleChannelReorder,
    handleChannelSettingsSave: ctx.handleChannelSettingsSave,
    handleCreateCategorySubmit: ctx.handleCreateCategorySubmit,
    handleCreateChannelModalSubmit: ctx.handleCreateChannelModalSubmit,
    handleCreateChannelSubmit: ctx.handleCreateChannelSubmit,
    handleCreateGroupDM: ctx.handleCreateGroupDM,
    handleKickGroupDmMember: ctx.handleKickGroupDmMember,
    handleLeaveGroupDm: ctx.handleLeaveGroupDm,
    handleCreateServer: ctx.handleCreateServer,
    handleExpandedProfileNoteFromLayout:
      ctx.handleExpandedProfileNoteFromLayout,
    expandDmProfileToFullModal: ctx.expandDmProfileToFullModal,
    handleExpandedProfileOpenDM: ctx.handleExpandedProfileOpenDM,
    handleMemberPopoutQuickDm: ctx.handleMemberPopoutQuickDm,
    handleExpandedProfileOpenProfile: ctx.handleExpandedProfileOpenProfile,
    handleExpandedProfileOpenServer: ctx.handleExpandedProfileOpenServer,
    handleExpandedProfileRemoveFriend: ctx.handleExpandedProfileRemoveFriend,
    handleExpandedProfileSendFriendRequest:
      ctx.handleExpandedProfileSendFriendRequest,
    handleExpandedProfileCancelOutgoingFriendRequest:
      ctx.handleExpandedProfileCancelOutgoingFriendRequest,
    handleExpandedProfileAcceptIncomingFriendRequest:
      ctx.handleExpandedProfileAcceptIncomingFriendRequest,
    handleExpandedProfileDeclineIncomingFriendRequest:
      ctx.handleExpandedProfileDeclineIncomingFriendRequest,
    handleProfileBlockUser: ctx.handleProfileBlockUser,
    handleProfileUnblockUser: ctx.handleProfileUnblockUser,
    handleProfileReportUser: ctx.handleProfileReportUser,
    isExpandedProfileTargetBlocked: ctx.isExpandedProfileTargetBlocked,
    isMemberPopoutTargetBlocked: ctx.isMemberPopoutTargetBlocked,
    openAddServerModal: ctx.openAddServerModal,
    isEchoGraphId: ctx.isEchoGraphId,
    handleGoToChannel: ctx.handleGoToChannel,
    handleGoToMessage: ctx.handleGoToMessage,
    handleInviteFriend: ctx.handleInviteFriend,
    handleJoinDiscoverableServer: ctx.handleJoinDiscoverableServer,
    handleJoinVoice: ctx.handleJoinVoice,
    handleJoinVoiceIfAllowed: ctx.handleJoinVoiceIfAllowed,
    handleJoinWithInviteLink: ctx.handleJoinWithInviteLink,
    handleLeaveVoice: ctx.handleLeaveVoice,
    handleChannelVoicePanelLeave: ctx.handleChannelVoicePanelLeave,
    handleModerateUser: ctx.handleModerateUser,
    handlePinMessage: ctx.handlePinMessage,
    handlePollVote: ctx.handlePollVote,
    handleReact: ctx.handleReact,
    handleAcceptMessageRequest: ctx.handleAcceptMessageRequest,
    handleDmMarkRead: ctx.handleDmMarkRead,
    hideDmFromInboxUser: ctx.hideDmFromInboxUser,
    hideDmFromInboxGroup: ctx.hideDmFromInboxGroup,
    isDmInboxUserFavorite: ctx.isDmInboxUserFavorite,
    isDmInboxGroupFavorite: ctx.isDmInboxGroupFavorite,
    toggleFavoriteDmInbox: ctx.toggleFavoriteDmInbox,
    handleSelectGroupDM: ctx.handleSelectGroupDM,
    handleServerDeleted: ctx.handleServerDeleted,
    handleServerNotificationSave: ctx.handleServerNotificationSave,
    handleServerRailInvite: ctx.handleServerRailInvite,
    handleServerRailLeave: ctx.handleServerRailLeave,
    handleServerRailNotificationSettings:
      ctx.handleServerRailNotificationSettings,
    handleServerRailSettings: ctx.handleServerRailSettings,
    handleServerRailMarkAllRead: ctx.handleServerRailMarkAllRead,
    handleDmRailMarkAllRead: ctx.handleDmRailMarkAllRead,
    handleStartRolePreview: ctx.handleStartRolePreview,
    handleStartRolePreview_2: ctx.handleStartRolePreview,
    handleUnpinMessage: ctx.handleUnpinMessage,
    showNsfwChatGate: ctx.showNsfwChatGate,
    showWelcomeBackSlimBanner: ctx.showWelcomeBackSlimBanner,
    acknowledgeNsfwChannel: ctx.acknowledgeNsfwChannel,
    declineNsfwGate: ctx.declineNsfwGate,
    handleUpdateCustomStatus: ctx.handleUpdateCustomStatus,
    handleUpdateGroupFromSettings: ctx.handleUpdateGroupFromSettings,
    onRemoveGroupDmMember: ctx.onRemoveGroupDmMember,
    onLeaveGroupDm: ctx.onLeaveGroupDm,
    onOpenAddMembersToGroupDm: ctx.onOpenAddMembersToGroupDm,
    handleVcModerate: ctx.handleVcModerate,
    hasGuildChannelChrome: ctx.hasGuildChannelChrome,
    hydrateEchoFromApi: ctx.hydrateEchoFromApi,
    ignoreMessageRequest: ctx.ignoreMessageRequest,
    icons: ctx.icons,
    inviteLinkForServer: ctx.inviteLinkForServer,
    inviteLinkFromApi: ctx.inviteLinkFromApi,
    inviteLinkLookupPending: ctx.inviteLinkLookupPending,
    inviteLinkFromSelectedServer: ctx.inviteLinkFromSelectedServer,
    inviteApplicationsEnabled: ctx.inviteApplicationsEnabled,
    inviteJoinLinksEnabled: ctx.inviteJoinLinksEnabled,
    inviteCanCreateDirectHexInvite: ctx.inviteCanCreateDirectHexInvite,
    directHexInviteLink: ctx.directHexInviteLink,
    directHexInviteBusy: ctx.directHexInviteBusy,
    createDirectHexInvite: ctx.createDirectHexInvite,
    inviteableFriends: ctx.inviteableFriends,
    isAddServerModalOpen: ctx.isAddServerModalOpen,
    authModalInitialLoginEntry: ctx.authModalInitialLoginEntry,
    authModalPasskeyOnOpen: ctx.authModalPasskeyOnOpen,
    authModalInitialTab: ctx.authModalInitialTab,
    authModalInitialSubView: ctx.authModalInitialSubView,
    openAuthModal: ctx.openAuthModal,
    isAuthModalOpen: ctx.isAuthModalOpen,
    isAuthenticated: ctx.isAuthenticated,
    isCompactShell: ctx.isCompactShell,
    isCompactGuildSplitShell: ctx.isCompactGuildSplitShell,
    isCompactPhoneShell: ctx.isCompactPhoneShell,
    useCompactPhoneTabShell: ctx.useCompactPhoneTabShell,
    mobileBottomTab: ctx.mobileBottomTab,
    mobileHomeStack: ctx.mobileHomeStack,
    mobileServersStack: ctx.mobileServersStack,
    mobileChannelSheetOpen: ctx.mobileChannelSheetOpen,
    mobileMembersOverlayOpen: ctx.mobileMembersOverlayOpen,
    isCreateCategoryModalOpen: ctx.isCreateCategoryModalOpen,
    isCreateChannelModalOpen: ctx.isCreateChannelModalOpen,
    isDMPanelOpen: ctx.isDMPanelOpen,
    isDmUiContext: ctx.isDmUiContext,
    isExpandedProfileFriend: ctx.isExpandedProfileFriend,
    isExpandedProfileOutgoingRequest: ctx.isExpandedProfileOutgoingRequest,
    isEchoUserFriend: ctx.isEchoUserFriend,
    isEchoUserIncomingFriendRequest: ctx.isEchoUserIncomingFriendRequest,
    isEchoUserOutgoingFriendRequest: ctx.isEchoUserOutgoingFriendRequest,
    isExpandedProfileModalOpen: ctx.isExpandedProfileModalOpen,
    isExpandedProfileSidePanel: ctx.isExpandedProfileSidePanel,
    isExploreView: ctx.isExploreView,
    isGroupDM: ctx.isGroupDM,
    isGroupDMModalOpen: ctx.isGroupDMModalOpen,
    isGroupDMSettingsOpen: ctx.isGroupDMSettingsOpen,
    groupDmSettingsInitialFocus: ctx.groupDmSettingsInitialFocus,
    isGroupOverviewOpen: ctx.isGroupOverviewOpen,
    isGuest: ctx.isGuest,
    isGuestDisplayNameModalOpen: ctx.isGuestDisplayNameModalOpen,
    isGuestWelcomePrefsModalOpen: ctx.isGuestWelcomePrefsModalOpen,
    isGuestUpgradeModalOpen: ctx.isGuestUpgradeModalOpen,
    isGuestCaptchaModalOpen: ctx.isGuestCaptchaModalOpen,
    guestCaptchaSiteKey: ctx.guestCaptchaSiteKey,
    isInDMChat: ctx.isInDMChat,
    isInDMMode: ctx.isInDMMode,
    isInviteModalOpen: ctx.isInviteModalOpen,
    inviteModalVoiceChannelId: ctx.inviteModalVoiceChannelId,
    inviteModalVoiceChannelName: ctx.inviteModalVoiceChannelName,
    isLeaveServerModalOpen: ctx.isLeaveServerModalOpen,
    isJoinServerConfirmModalOpen: ctx.isJoinServerConfirmModalOpen,
    joinServerConfirmPreview: ctx.joinServerConfirmPreview,
    joinServerConfirmBusy: ctx.joinServerConfirmBusy,
    isMemberPopoutOpen: ctx.isMemberPopoutOpen,
    isMemberPopoutFriend: ctx.isMemberPopoutFriend,
    isMemberPopoutCanSendFriendRequest: ctx.isMemberPopoutCanSendFriendRequest,
    isMoreServersCompact: ctx.isMoreServersCompact,
    isMoreServersPanelOpen: ctx.isMoreServersPanelOpen,
    isMoreServersPinned: ctx.isMoreServersPinned,
    isPinsDropdownOpen: ctx.isPinsDropdownOpen,
    isRolePreviewActiveForServer: ctx.isRolePreviewActiveForServer,
    isSearchActive: ctx.isSearchActive,
    isSelfProfilePopoutOpen: ctx.isSelfProfilePopoutOpen,
    isServerEmptyOnboarding: ctx.isServerEmptyOnboarding,
    isServerNotificationSettingsOpen: ctx.isServerNotificationSettingsOpen,
    isServerSettingsModalOpen: ctx.isServerSettingsModalOpen,
    isSettingsModalOpen: ctx.isSettingsModalOpen,
    settingsModalInitialSection: ctx.settingsModalInitialSection,
    settingsModalActiveSection: ctx.settingsModalActiveSection,
    serverSettingsModalInitialSection: ctx.serverSettingsModalInitialSection,
    serverSettingsModalActiveSection: ctx.serverSettingsModalActiveSection,
    isViewingVoiceChannel: ctx.isViewingVoiceChannel,
    joinEchoServerWithInviteRaw: ctx.joinEchoServerWithInviteRaw,
    leaveServerModalServerName: ctx.leaveServerModalServerName,
    leaveServerModalVariant: ctx.leaveServerModalVariant,
    mainContentColumns: ctx.mainContentColumns,
    mainContentColumnsEffective: ctx.mainContentColumnsEffective,
    mainSurface: ctx.mainSurface,
    markActiveChannelAsRead: ctx.markActiveChannelAsRead,
    handleChannelMarkRead: ctx.handleChannelMarkRead,
    memberListResolveHighestRole: ctx.memberListResolveHighestRole,
    memberListRoleManagement: ctx.memberListRoleManagement,
    memberListUsers: ctx.memberListUsers,
    serverSettingsMemberUsers: ctx.serverSettingsMemberUsers,
    usersForChannelPanel: ctx.usersForChannelPanel,
    usersForMentionAutocomplete: ctx.usersForMentionAutocomplete,
    rolesForMentionAutocomplete: ctx.rolesForMentionAutocomplete,
    memberPopoutOpenRolesPanel: ctx.memberPopoutOpenRolesPanel,
    memberPanelCollapsed: ctx.memberPanelCollapsed,
    memberListShowGuests: ctx.memberListShowGuests,
    memberPanelAutoCollapseUserOverride:
      ctx.memberPanelAutoCollapseUserOverride,
    markMemberPanelExpandedByUser: ctx.markMemberPanelExpandedByUser,
    markMemberPanelCollapsedByUser: ctx.markMemberPanelCollapsedByUser,
    memberPanelCollapsedEffective: ctx.memberPanelCollapsedEffective,
    memberPanelWidth: ctx.memberPanelWidth,
    memberPopoutAnchor: ctx.memberPopoutAnchor,
    workspace: ctx.workspace,
    moderationAction: ctx.moderationAction,
    moderationModalOpen: ctx.moderationModalOpen,
    moderationTargetUser: ctx.moderationTargetUser,
    moderationTargetUserId: ctx.moderationTargetUserId,
    newlyCreatedServerId: ctx.newlyCreatedServerId,
    onCategorySettingsModalOpenUpdate: ctx.onCategorySettingsModalOpenUpdate,
    onChannelSettingsModalOpenUpdate: ctx.onChannelSettingsModalOpenUpdate,
    onExpandedProfileModalUpdate: ctx.onExpandedProfileModalUpdate,
    onJoinVoice: ctx.onJoinVoice,
    onJoinVoiceUi: ctx.onJoinVoiceUi,
    onLeaveServerModalUpdate: ctx.onLeaveServerModalUpdate,
    onLeaveVoice: ctx.onLeaveVoice,
    onLeaveVoiceUi: ctx.onLeaveVoiceUi,
    confirmLeaveServerFromModal: ctx.confirmLeaveServerFromModal,
    confirmJoinServerFromModal: ctx.confirmJoinServerFromModal,
    onJoinServerConfirmModalUpdate: ctx.onJoinServerConfirmModalUpdate,
    isServerApplicationModalOpen: ctx.isServerApplicationModalOpen,
    serverApplicationPayload: ctx.serverApplicationPayload,
    serverApplicationBusy: ctx.serverApplicationBusy,
    onServerApplicationModalUpdate: ctx.onServerApplicationModalUpdate,
    confirmServerApplicationSubmittedFromModal:
      ctx.confirmServerApplicationSubmittedFromModal,
    continueAsGuest: ctx.continueAsGuest,
    onModerationModalConfirm: ctx.onModerationModalConfirm,
    onMemberPopoutOpenUpdate: ctx.onMemberPopoutOpenUpdate,
    onGuestAccountUpgraded: ctx.onGuestAccountUpgraded,
    onGuestCaptchaVerified: ctx.onGuestCaptchaVerified,
    onSearchInput: ctx.onSearchInput,
    onUserSettingsModalUpdate: ctx.onUserSettingsModalUpdate,
    onServerSettingsModalUpdate: ctx.onServerSettingsModalUpdate,
    onSettingsModalActiveSectionUpdate: ctx.onSettingsModalActiveSectionUpdate,
    onServerSettingsModalActiveSectionUpdate:
      ctx.onServerSettingsModalActiveSectionUpdate,
    onVcChatButtonClick: ctx.onVcChatButtonClick,
    handleMinimizeVoiceView: ctx.handleMinimizeVoiceView,
    openCategorySettings: ctx.openCategorySettings,
    openChannelSettings: ctx.openChannelSettings,
    openCreateCategoryModal: ctx.openCreateCategoryModal,
    openCreateChannelModal: ctx.openCreateChannelModal,
    openExpandedProfileDmFromComposable:
      ctx.openExpandedProfileDmFromComposable,
    openExpandedProfileFromMemberPopout:
      ctx.openExpandedProfileFromMemberPopout,
    openExpandedProfileFromSelfPopout: ctx.openExpandedProfileFromSelfPopout,
    openExpandedProfilePanelForUserId: ctx.openExpandedProfilePanelForUserId,
    openExtendedProfileModalForUserId: ctx.openExtendedProfileModalForUserId,
    openGroupDMModal: ctx.openGroupDMModal,
    openGroupOverviewPanel: ctx.openGroupOverviewPanel,
    openDmInboxFromRailOverflow: ctx.openDmInboxFromRailOverflow,
    openGuestUpgradeModal: ctx.openGuestUpgradeModal,
    openGroupSettingsFromHeader: ctx.openGroupSettingsFromHeader,
    openMemberProfile: ctx.openMemberProfile,
    openMemberProfileFromMemberColumn: ctx.openMemberProfileFromMemberColumn,
    openProfileFromContextMenu: ctx.openProfileFromContextMenu,
    openSelfProfile: ctx.openSelfProfile,
    openServerFromMore: ctx.openServerFromMore,
    openServerSurface: ctx.openServerSurface,
    openServerNotificationSettings: ctx.openServerNotificationSettings,
    openServerSettings: ctx.openServerSettings,
    openServerSettingsIfAllowed: ctx.openServerSettingsIfAllowed,
    openServerSettingsFromUrl: ctx.openServerSettingsFromUrl,
    openInviteModal: ctx.openInviteModal,
    openUserSettingsModal: ctx.openUserSettingsModal,
    openUserSettingsToDiscordFromAddServer:
      ctx.openUserSettingsToDiscordFromAddServer,
    paginatedSearchResults: ctx.paginatedSearchResults,
    pfpBarExpanded: ctx.pfpBarExpanded,
    pinMessage: ctx.pinMessage,
    pinPreview: ctx.pinPreview,
    pinnedMessageIdsForCurrentChannel: ctx.pinnedMessageIdsForCurrentChannel,
    pinnedMessagesForDropdown: ctx.pinnedMessagesForDropdown,
    pinsButtonRefDm: ctx.pinsButtonRefDm,
    pinsButtonRefServer: ctx.pinsButtonRefServer,
    pinsDropdownRect: ctx.pinsDropdownRect,
    previewCanModerateMembers: ctx.previewCanModerateMembers,
    previewHasUiPermission: ctx.previewHasUiPermission,
    profileNotes: ctx.profileNotes,
    rawCategoriesForServer: ctx.rawCategoriesForServer,
    recordReaction: ctx.recordReaction,
    removeReactionFavorite: ctx.removeReactionFavorite,
    refreshEchoRoleData: ctx.refreshEchoRoleData,
    reorderVisibleServers: ctx.reorderVisibleServers,
    removeFilter: ctx.removeFilter,
    resetChannelWidth: ctx.resetChannelWidth,
    resetDmPanelWidth: ctx.resetDmPanelWidth,
    resetMemberWidth: ctx.resetMemberWidth,
    resetVoiceSideChatWidth: ctx.resetVoiceSideChatWidth,
    resolvePreviewChannelPermission: ctx.resolvePreviewChannelPermission,
    returnFromMessageRequests: ctx.returnFromMessageRequests,
    rolePreview: ctx.rolePreview,
    searchError: ctx.searchError,
    searchLoading: ctx.searchLoading,
    searchResultMessages: ctx.searchResultMessages,
    searchResultPage: ctx.searchResultPage,
    searchScopeHint: ctx.searchScopeHint,
    searchText: ctx.searchText,
    selectDM: ctx.selectDM,
    selectDMTab: ctx.selectDMTab,
    selectIncomingDmFromRail: ctx.selectIncomingDmFromRail,
    selectIncomingGroupDmFromRail: ctx.selectIncomingGroupDmFromRail,
    selectExploreTab: ctx.selectExploreTab,
    selectMessageRequest: ctx.selectMessageRequest,
    selectServersTab: ctx.selectServersTab,
    selectServersRailOnly: ctx.selectServersRailOnly,
    selectedDMUserId: ctx.selectedDMUserId,
    selectedMessageRequestId: ctx.selectedMessageRequestId,
    dmMentionNotifications: ctx.dmMentionNotifications,
    mentionNotificationHydrationLoading:
      ctx.mentionNotificationHydrationLoading,
    resolveDmMentionNotificationChannelLabel:
      ctx.resolveDmMentionNotificationChannelLabel,
    resolveDmMentionNotificationAuthorName:
      ctx.resolveDmMentionNotificationAuthorName,
    resolveDmMentionNotificationRowPreview:
      ctx.resolveDmMentionNotificationRowPreview,
    dmNotificationReadStateByChannelId: ctx.dmNotificationReadStateByChannelId,
    mentionNotificationCategoriesByServer:
      ctx.mentionNotificationCategoriesByServer,
    mentionNotificationServers: ctx.mentionNotificationServers,
    dmNotificationsReadPreset: ctx.dmNotificationsReadPreset,
    dmNotificationsSourceKey: ctx.dmNotificationsSourceKey,
    onOpenMentionNotification: ctx.onOpenMentionNotification,
    onMarkMentionNotificationRead: ctx.onMarkMentionNotificationRead,
    selectedServer: ctx.selectedServer,
    selfProfile: ctx.selfProfile,
    selfProfileAnchor: ctx.selfProfileAnchor,
    sendFriendRequest: ctx.sendFriendRequest,
    sendMessage: ctx.sendMessage,
    forwardModalOpen: ctx.forwardModalOpen,
    forwardPickerDestinations: ctx.forwardPickerDestinations,
    forwardModalSourceSummary: ctx.forwardModalSourceSummary,
    openForwardMessagePicker: ctx.openForwardMessagePicker,
    closeForwardMessagePicker: ctx.closeForwardMessagePicker,
    submitForwardedMessage: ctx.submitForwardedMessage,
    serverNotificationLevelsMap: ctx.serverNotificationLevelsMap,
    serverPingKindByServerId: ctx.serverPingKindByServerId,
    serverPingBubbleByServerId: ctx.serverPingBubbleByServerId,
    serverPingChannelDotsByServerId: ctx.serverPingChannelDotsByServerId,
    serverUnreadActivityDotByServerId: ctx.serverUnreadActivityDotByServerId,
    channelMissedActivityByChannelId: ctx.channelMissedActivityByChannelId,
    serverSettingsCanManageRoles: ctx.serverSettingsCanManageRoles,
    serverSettingsCanManageServer: ctx.serverSettingsCanManageServer,
    serverStore: ctx.serverStore,
    sessionEndedMessage: ctx.sessionEndedMessage,
    discordBotExportReadyBanner: ctx.discordBotExportReadyBanner,
    dismissDiscordBotExportReadyBanner: ctx.dismissDiscordBotExportReadyBanner,
    shellNavState: ctx.shellNavState,
    showApiFetchErrorBanner: ctx.showApiFetchErrorBanner,
    socketSendMessage: ctx.socketSendMessage,
    startChannelResize: ctx.startChannelResize,
    startDmCall: ctx.startDmCall,
    startDmCallWithUserId: ctx.startDmCallWithUserId,
    startDmPanelResize: ctx.startDmPanelResize,
    startGroupCall: ctx.startGroupCall,
    startGroupCallWithId: ctx.startGroupCallWithId,
    startMemberResize: ctx.startMemberResize,
    startRolePreview: ctx.startRolePreview,
    startVoiceSideChatResize: ctx.startVoiceSideChatResize,
    syncVanityAcrossServerLists: ctx.syncVanityAcrossServerLists,
    toggleMoreServersPanel: ctx.toggleMoreServersPanel,
    togglePinsDropdown: ctx.togglePinsDropdown,
    toggleReaction: ctx.toggleReaction,
    toggleVoiceSideChat: ctx.toggleVoiceSideChat,
    voiceMobileSheetLevel: ctx.voiceMobileSheetLevel,
    bumpVoiceMobileChatFromCallScrollUp:
      ctx.bumpVoiceMobileChatFromCallScrollUp,
    bumpVoiceMobileChatFromCallScrollDown:
      ctx.bumpVoiceMobileChatFromCallScrollDown,
    topReactions: ctx.topReactions,
    totalPages: ctx.totalPages,
    unpinMessage: ctx.unpinMessage,
    updateCurrentUserStatus: ctx.updateCurrentUserStatus,
    updateProfileNote: ctx.updateProfileNote,
    updateVcVideoIfAllowed: ctx.updateVcVideoIfAllowed,
    vcDeafened: ctx.vcDeafened,
    applyVcDeafened: ctx.applyVcDeafened,
    applyVcMuted: ctx.applyVcMuted,
    vcMuted: ctx.vcMuted,
    vcScreenshare: ctx.vcScreenshare,
    vcVideo: ctx.vcVideo,
    isScreenSharePickerOpen: ctx.isScreenSharePickerOpen,
    isDesktopStreamingControlOpen: ctx.isDesktopStreamingControlOpen,
    desktopStreamingControlMode: ctx.desktopStreamingControlMode,
    desktopStreamingPreferences: ctx.desktopStreamingPreferences,
    fullscreenStreamParticipantId: ctx.fullscreenStreamParticipantId,
    vcActivityUi: ctx.vcActivityUi,
    openVcActivityPicker: ctx.openVcActivityPicker,
    openVcActivityYoutubeBrowse: ctx.openVcActivityYoutubeBrowse,
    openVcActivityWatchTogether: ctx.openVcActivityWatchTogether,
    openVcActivityWordle: ctx.openVcActivityWordle,
    openVcActivityHangman: ctx.openVcActivityHangman,
    openVcActivitySkriggles: ctx.openVcActivitySkriggles,
    openVcActivityTicTacToe: ctx.openVcActivityTicTacToe,
    openVcActivityOpenGuessr: ctx.openVcActivityOpenGuessr,
    openVcActivitySkribblIo: ctx.openVcActivitySkribblIo,
    openVcActivityGarticPhone: ctx.openVcActivityGarticPhone,
    openVcActivityKrunker: ctx.openVcActivityKrunker,
    openVcActivityCodenames: ctx.openVcActivityCodenames,
    openVcActivityRichup: ctx.openVcActivityRichup,
    openVcActivityGooberDash: ctx.openVcActivityGooberDash,
    openVcActivitySmashKarts: ctx.openVcActivitySmashKarts,
    openVcActivityClusterRush: ctx.openVcActivityClusterRush,
    setVcActivityYoutubeVideo: ctx.setVcActivityYoutubeVideo,
    setVcYoutubeBrowseOpen: ctx.setVcYoutubeBrowseOpen,
    addVcYoutubeToQueue: ctx.addVcYoutubeToQueue,
    removeVcYoutubeFromQueue: ctx.removeVcYoutubeFromQueue,
    moveVcYoutubeInQueue: ctx.moveVcYoutubeInQueue,
    playVcYoutubeAtIndex: ctx.playVcYoutubeAtIndex,
    playVcYoutubeNext: ctx.playVcYoutubeNext,
    playVcYoutubePrevious: ctx.playVcYoutubePrevious,
    setWatchTogetherLobbyRole: ctx.setWatchTogetherLobbyRole,
    ensureWatchTogetherSessionId: ctx.ensureWatchTogetherSessionId,
    patchWatchTogetherUi: ctx.patchWatchTogetherUi,
    setWatchTogetherBrowseOpen: ctx.setWatchTogetherBrowseOpen,
    startWatchTogetherSession: ctx.startWatchTogetherSession,
    playWatchTogetherAtIndex: ctx.playWatchTogetherAtIndex,
    closeVcActivity: ctx.closeVcActivity,
    vcYoutubeRemotePlayback: ctx.vcYoutubeRemotePlayback,
    publishVcYoutubePlaybackSync: ctx.publishVcYoutubePlaybackSync,
    vcYoutubePlaybackShouldPublish: ctx.vcYoutubePlaybackShouldPublish,
    vcWatchTogetherRemotePlayback: ctx.vcWatchTogetherRemotePlayback,
    publishVcWatchTogetherPlaybackSync: ctx.publishVcWatchTogetherPlaybackSync,
    vcWatchTogetherPlaybackShouldPublish:
      ctx.vcWatchTogetherPlaybackShouldPublish,
    handleScreenSharePickerConfirm: ctx.handleScreenSharePickerConfirm,
    openDesktopStreamingControl: ctx.openDesktopStreamingControl,
    closeDesktopStreamingControl: ctx.closeDesktopStreamingControl,
    handleDesktopStreamingControlConfirm:
      ctx.handleDesktopStreamingControlConfirm,
    handleToggleScreenshare: ctx.handleToggleScreenshare,
    handleStopScreenShare: ctx.handleStopScreenShare,
    getLocalScreenTrack: ctx.getLocalScreenTrack,
    getLocalCameraTrack: ctx.getLocalCameraTrack,
    getRemoteParticipantVolume: ctx.getRemoteParticipantVolume,
    setRemoteParticipantVolume: ctx.setRemoteParticipantVolume,
    voiceSideChatCollapsed: ctx.voiceSideChatCollapsed,
    voiceSideChatWidth: ctx.voiceSideChatWidth,
    votePoll: ctx.votePoll,
    welcomeBackExploreGate: ctx.welcomeBackExploreGate,
    welcomeBackExploreMemberEmptyDirectory:
      ctx.welcomeBackExploreMemberEmptyDirectory,
    inviteLandingActive: ctx.inviteLandingActive,
    inviteLandingPreview: ctx.inviteLandingPreview,
    inviteLandingLoading: ctx.inviteLandingLoading,
    inviteLandingError: ctx.inviteLandingError,
    inviteLandingPersistBeforeOAuth: ctx.inviteLandingPersistBeforeOAuth,
    watchActiveChannelWithServerChange: ctx.watchActiveChannelWithServerChange,
    isEchoUserBlocked: ctx.isEchoUserBlocked,
    isPersistedEchoDmThread: ctx.isPersistedEchoDmThread,
    workspaceReady: ctx.workspaceReady,
    onEchoMessageFailedGuest: ctx.onEchoMessageFailedGuest,
    dispatchNav: ctx.dispatchNav,
    isServerUnread: ctx.isServerUnread,
    isChannelActive: ctx.isChannelActive,
    isMemberProfileOpen: ctx.isMemberProfileOpen,
    onOpenCreateChannel: ctx.onOpenCreateChannel,
    toggleChannelPanel: ctx.toggleChannelPanel,
    toggleMemberList: ctx.toggleMemberList,
    openDMPanel: ctx.openDMPanel,
    memberListCollapsed: ctx.memberListCollapsed,
    memberListWidth: ctx.memberListWidth,
    memberProfileUserId: ctx.memberProfileUserId,
    membersForMemberList: ctx.membersForMemberList,
    searchActiveTab: ctx.searchActiveTab,
    searchFilter: ctx.searchFilter,
    searchIsLoading: ctx.searchIsLoading,
    searchResults: ctx.searchResults,
    searchStatus: ctx.searchStatus,
    selectedServerId: ctx.selectedServerId,
    servers: ctx.servers,
  };

  // Back-compat: `AppLayout.vue` still destructures a number of legacy `_foo` names.
  // Mirror every public key as `_key` without breaking the canonical names.
  for (const [key, value] of Object.entries(exposed)) {
    if (key.startsWith('_')) continue;
    exposed[`_${key}`] = value;
  }

  return exposed as AppLayoutControllerContext & Record<string, unknown>;
}
