import type { AppLayoutControllerContext } from '@/features/layout/composables/controller/appLayoutControllerTypes';

export type AppLayoutChatSurfaceVoiceActivityKeys =
  | 'vcHangmanActivity'
  | 'hangmanRosterUserIds'
  | 'hangmanGameRoomConnected'
  | 'hangmanGameRoomLastError'
  | 'commitVcHangmanWord'
  | 'requestVcHangmanGuessLetter'
  | 'requestVcHangmanNextRound'
  | 'wordlineView'
  | 'submitWordlineGuess'
  | 'setWordlineMode'
  | 'vcSkrigglesActivity'
  | 'skrigglesRosterUserIds'
  | 'skrigglesCanvasEvents'
  | 'commitSkrigglesWordChoice'
  | 'submitSkrigglesGuess'
  | 'updateSkrigglesSettings'
  | 'startSkrigglesGame'
  | 'advanceSkrigglesRound'
  | 'publishSkrigglesStrokeBatch'
  | 'publishSkrigglesCanvasCmd'
  | 'publishSkrigglesCanvasSnapshot'
  | 'tickSkrigglesTimers'
  | 'vcTicTacToeActivity'
  | 'vcTicTacToePendingInvite'
  | 'sendVcTicTacToeChallenge'
  | 'respondVcTicTacToeInvite'
  | 'dismissVcTicTacToeInvite'
  | 'requestVcTicTacToeMove'
  | 'requestVcTicTacToeRematch'
  | 'vcCodenamesActivity'
  | 'codenamesRosterUserIds'
  | 'vcCodenamesSpymasterKey'
  | 'commitVcCodenamesDeal'
  | 'requestVcCodenamesSetup'
  | 'requestVcCodenamesClue'
  | 'requestVcCodenamesReveal'
  | 'requestVcCodenamesEndTurn'
  | 'requestVcCodenamesNewGame'
  | 'requestVcCodenamesPushKeyToOrchestrator'
  | 'openVcActivityPicker'
  | 'openVcActivityYoutubeBrowse'
  | 'openVcActivityWatchTogether'
  | 'openVcActivityWordle'
  | 'openVcActivityHangman'
  | 'openVcActivitySkriggles'
  | 'openVcActivityTicTacToe'
  | 'openVcActivityOpenGuessr'
  | 'openVcActivitySkribblIo'
  | 'openVcActivityGarticPhone'
  | 'openVcActivityKrunker'
  | 'openVcActivityCodenames'
  | 'openVcActivityRichup'
  | 'openVcActivityGooberDash'
  | 'openVcActivitySmashKarts'
  | 'openVcActivityClusterRush'
  | 'setVcActivityYoutubeVideo'
  | 'setVcYoutubeBrowseOpen'
  | 'addVcYoutubeToQueue'
  | 'removeVcYoutubeFromQueue'
  | 'moveVcYoutubeInQueue'
  | 'playVcYoutubeAtIndex'
  | 'playVcYoutubeNext'
  | 'playVcYoutubePrevious'
  | 'setWatchTogetherLobbyRole'
  | 'ensureWatchTogetherSessionId'
  | 'patchWatchTogetherUi'
  | 'setWatchTogetherBrowseOpen'
  | 'startWatchTogetherSession'
  | 'playWatchTogetherAtIndex'
  | 'closeVcActivity'
  | 'vcYoutubeRemotePlayback'
  | 'publishVcYoutubePlaybackSync'
  | 'vcYoutubePlaybackShouldPublish'
  | 'vcWatchTogetherRemotePlayback'
  | 'publishVcWatchTogetherPlaybackSync'
  | 'vcWatchTogetherPlaybackShouldPublish';

export type AppLayoutChatSurfaceVoiceActivitySlice = Pick<
  AppLayoutControllerContext,
  AppLayoutChatSurfaceVoiceActivityKeys
>;
