/**
 * Built-in wordlists for the banned-words filter, grouped by category.
 *
 * Each list contains lowercase words/phrases. The matcher normalises input
 * before comparison so casing and basic l33t-speak substitutions are handled.
 */

import type { BannedWordCategory } from '../../../../../../contracts/types/bannedWords';

const PROFANITY: readonly string[] = [
  'fuck',
  'fucking',
  'fucked',
  'fucker',
  'fuckers',
  'shit',
  'shitting',
  'shitty',
  'bullshit',
  'ass',
  'asshole',
  'assholes',
  'damn',
  'damnit',
  'goddamn',
  'bitch',
  'bitches',
  'bitching',
  'bastard',
  'bastards',
  'crap',
  'crappy',
  'piss',
  'pissed',
  'pissing',
  'hell',
  'wtf',
  'stfu',
  'lmfao',
];

const SLURS: readonly string[] = [
  'nigger',
  'nigga',
  'niggers',
  'niggas',
  'faggot',
  'faggots',
  'fag',
  'fags',
  'retard',
  'retarded',
  'retards',
  'tranny',
  'trannies',
  'dyke',
  'dykes',
  'spic',
  'spics',
  'kike',
  'kikes',
  'chink',
  'chinks',
  'wetback',
  'wetbacks',
  'coon',
  'coons',
  'gook',
  'gooks',
  'beaner',
  'beaners',
  'towelhead',
  'towelheads',
  'raghead',
  'ragheads',
];

const SEXUAL_CONTENT: readonly string[] = [
  'porn',
  'porno',
  'pornography',
  'hentai',
  'xxx',
  'dick',
  'dicks',
  'cock',
  'cocks',
  'pussy',
  'pussies',
  'cum',
  'cumming',
  'cumshot',
  'tits',
  'titties',
  'boobs',
  'blowjob',
  'blowjobs',
  'handjob',
  'handjobs',
  'dildo',
  'dildos',
  'masturbate',
  'masturbating',
  'masturbation',
  'orgasm',
  'orgasms',
  'anal',
  'anus',
  'nipple',
  'nipples',
  'erection',
  'vagina',
  'vaginal',
  'penis',
  'clitoris',
  'ejaculate',
  'ejaculation',
];

const INSULTS: readonly string[] = [
  'idiot',
  'idiots',
  'idiotic',
  'stupid',
  'stupidity',
  'dumb',
  'dumbass',
  'dumbasses',
  'moron',
  'morons',
  'moronic',
  'loser',
  'losers',
  'pathetic',
  'worthless',
  'trash',
  'scum',
  'scumbag',
  'scumbags',
  'creep',
  'creeps',
  'creepy',
  'freak',
  'freaks',
  'weirdo',
  'weirdos',
  'clown',
  'clowns',
  'degenerate',
  'degenerates',
  'imbecile',
  'imbeciles',
  'dimwit',
  'dimwits',
  'twit',
  'twits',
  'fool',
  'fools',
  'ignorant',
];

const LISTS: Record<BannedWordCategory, readonly string[]> = {
  profanity: PROFANITY,
  slurs: SLURS,
  sexual_content: SEXUAL_CONTENT,
  insults: INSULTS,
};

export function getWordlist(category: BannedWordCategory): readonly string[] {
  return LISTS[category] ?? [];
}

export function getAllWordlists(): Record<
  BannedWordCategory,
  readonly string[]
> {
  return LISTS;
}
