/**
 * LAN dev + LiveKit for other devices on your network.
 * Writes `.env.lan` and `infra/livekit/livekit.runtime.yaml` (gitignored), then use `npm run dev:lan`.
 */
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(__dirname, '..');

function readEnvFile(filePath) {
  const out = {};
  if (!fs.existsSync(filePath)) return out;
  let text = fs.readFileSync(filePath, 'utf8');
  if (text.charCodeAt(0) === 0xfeff) text = text.slice(1);
  for (const line of text.split(/\r?\n/)) {
    const s = line.trim();
    if (!s || s.startsWith('#')) continue;
    const eq = s.indexOf('=');
    if (eq <= 0) continue;
    const key = s.slice(0, eq).trim();
    let val = s.slice(eq + 1).trim();
    if (
      (val.startsWith('"') && val.endsWith('"')) ||
      (val.startsWith("'") && val.endsWith("'"))
    ) {
      val = val.slice(1, -1);
    }
    out[key] = val;
  }
  return out;
}

function parseArgIp() {
  const raw = process.argv.find((a) => a.startsWith('--ip='));
  if (!raw) return undefined;
  return raw.slice('--ip='.length).trim();
}

function detectLanIPv4() {
  const nets = os.networkInterfaces();
  const cand = [];
  for (const name of Object.keys(nets)) {
    for (const net of nets[name] || []) {
      const fam = net.family;
      if (fam !== 'IPv4' && fam !== 4) continue;
      if (net.internal) continue;
      const ip = net.address;
      if (ip.startsWith('169.254.')) continue;
      cand.push({ name, ip });
    }
  }
  const preferred = /wi-?fi|wlan|wlp|eth|eno|en0|en1|bridge/i;
  cand.sort(
    (a, b) =>
      (preferred.test(b.name) ? 1 : 0) - (preferred.test(a.name) ? 1 : 0),
  );
  return cand[0]?.ip;
}

function isIPv4(s) {
  return /^\d{1,3}(\.\d{1,3}){3}$/.test(s);
}

const baseEnv = readEnvFile(path.join(root, '.env'));
const fromCli = parseArgIp();
const ip =
  (fromCli && isIPv4(fromCli) ? fromCli : undefined) ||
  (baseEnv.ECHO_DEV_LAN_IP && isIPv4(baseEnv.ECHO_DEV_LAN_IP)
    ? baseEnv.ECHO_DEV_LAN_IP
    : undefined) ||
  detectLanIPv4();

if (!ip || !isIPv4(ip)) {
  console.error(
    'sync-lan-dev: could not determine a LAN IPv4. Set ECHO_DEV_LAN_IP in .env or run:\n' +
      '  node scripts/sync-lan-dev.mjs --ip=192.168.1.50',
  );
  process.exit(1);
}

const livekitBase = path.join(root, 'infra', 'livekit', 'livekit.yaml');
const livekitOut = path.join(root, 'infra', 'livekit', 'livekit.runtime.yaml');
if (!fs.existsSync(livekitBase)) {
  console.error('sync-lan-dev: missing', livekitBase);
  process.exit(1);
}

let yaml = fs.readFileSync(livekitBase, 'utf8');
if (!yaml.includes('- host: coturn')) {
  console.error(
    'sync-lan-dev: infra/livekit/livekit.yaml has no `- host: coturn` — not updating TURN host.',
  );
  process.exit(1);
}
if (!/^(\s*)node_ip:\s*127\.0\.0\.1\s*$/m.test(yaml)) {
  console.error(
    'sync-lan-dev: infra/livekit/livekit.yaml has no `node_ip: 127.0.0.1` — not updating ICE advertise IP.',
  );
  process.exit(1);
}

yaml = yaml.replace(/^(\s*-\s*)host:\s*coturn\s*$/m, `$1host: ${ip}`);
yaml = yaml.replace(/^(\s*)node_ip:\s*127\.0\.0\.1\s*$/m, `$1node_ip: ${ip}`);
fs.writeFileSync(livekitOut, yaml, 'utf8');

const envLanPath = path.join(root, '.env.lan');
const lines = [
  '# Generated by `npm run lan:sync` — safe to delete to turn off LAN overrides.',
  `ECHO_LIVEKIT_YAML=./infra/livekit/livekit.runtime.yaml`,
  `LIVEKIT_PUBLIC_URL=ws://${ip}:7880`,
  `ECHO_APP_PUBLIC_URL=http://${ip}:8080`,
  `CORS_ORIGIN=http://${ip}:8080,http://localhost:8080,http://127.0.0.1:8080`,
  '',
];
fs.writeFileSync(envLanPath, lines.join('\n'), 'utf8');

const hasLkKey = Boolean(
  baseEnv.LIVEKIT_API_KEY?.trim() && baseEnv.LIVEKIT_API_SECRET?.trim(),
);
if (!hasLkKey) {
  console.warn(
    '\nWarning: LIVEKIT_API_KEY / LIVEKIT_API_SECRET not found in .env — voice will stay disabled until you copy the LiveKit block from .env.example.\n',
  );
}

console.log(
  [
    'LAN dev files written:',
    `  ${path.relative(root, envLanPath)}`,
    `  ${path.relative(root, livekitOut)}`,
    '',
    `Open from another device: http://${ip}:8080`,
    '',
    'Next: recreate LiveKit if it was already running (picks up new YAML):',
    '  npm run db:down && npm run db:up',
    '  (or: npm run dev:lan  — runs sync then full dev stack)',
    '',
    'Windows firewall (once, elevated): npm run lan:firewall',
  ].join('\n'),
);
