import type { AssembleAppLayoutContextDeps } from './assembleAppLayoutControllerContext';
import type { WireAppLayoutVoiceAndRealtimeResult } from './wireAppLayoutVoiceAndRealtime';
import type { WireAppLayoutMessagingPhase3Extension } from './wireAppLayoutMessagingPhase3Extension';
import { useComputedRefAlias } from './useComputedRefAlias';
import { isEchoGraphId } from '@/utils/echoIds';
import { icons, getChannelDisplayName } from '@/assets/icons';

export type WireAppLayoutAssemblyInput = WireAppLayoutVoiceAndRealtimeResult &
  WireAppLayoutMessagingPhase3Extension;

export function buildAppLayoutAssemblyDeps(
  input: WireAppLayoutAssemblyInput,
): AssembleAppLayoutContextDeps {
  const $ = input;
  return {
    profile: {
      openMemberProfile: $.openMemberProfileForContext,
      activeMemberNote: $.activeMemberNote,
      expandedProfileNote: $.expandedProfileNote,
      updateProfileNote: $.updateProfileNote,
      openSelfProfile: $.openSelfProfile,
      openExpandedProfileFromMemberPopout:
        $.openExpandedProfileFromMemberPopout,
      openExpandedProfileFromSelfPopout: $.openExpandedProfileFromSelfPopout,
      openExpandedProfilePanelForUserId: $.openExpandedProfilePanelForUserId,
      openExtendedProfileModalForUserId: $.openExtendedProfileModalForUserId,
      expandDmProfileToFullModal: $.expandDmProfileToFullModal,
      handleExpandedProfileOpenProfile: $.handleExpandedProfileOpenProfile,
      handleExpandedProfileOpenDM: $.handleExpandedProfileOpenDM,
      handleMemberPopoutQuickDm: $.handleMemberPopoutQuickDm,
      handleExpandedProfileRemoveFriend: $.handleExpandedProfileRemoveFriend,
      handleExpandedProfileCancelOutgoingFriendRequest:
        $.handleExpandedProfileCancelOutgoingFriendRequest,
      handleProfileBlockUser: $.handleProfileBlockUser,
      handleProfileUnblockUser: $.handleProfileUnblockUser,
      handleProfileReportUser: $.handleProfileReportUser,
      isExpandedProfileTargetBlocked: $.isExpandedProfileTargetBlockedComputed,
      isExpandedProfileOutgoingRequest: $.isExpandedProfileOutgoingRequest,
      isMemberPopoutTargetBlocked: $.isMemberPopoutTargetBlockedComputed,
      isExpandedProfileFriend: $.isExpandedProfileFriend,
      isMemberPopoutFriend: $.isMemberPopoutFriend,
      isMemberPopoutCanSendFriendRequest: $.isMemberPopoutCanSendFriendRequest,
      memberListUsers: $.memberListUsers,
      serverSettingsMemberUsers: $.serverSettingsMemberUsers,
      usersForChannelPanel: $.usersForChannelPanel,
      usersForMentionAutocomplete: $.usersForMentionAutocomplete,
      rolesForMentionAutocomplete: $.rolesForMentionAutocomplete,
      onExpandedProfileModalUpdate: $.onExpandedProfileModalUpdate,
      expandedProfile: $.expandedProfile,
      selectDmUser: $.selectDmUser,
      selectDMTab: $.selectDMTab,
      sendFriendRequest: $.sendFriendRequest,
      memberPopoutOpenRolesPanel: $.memberPopoutOpenRolesPanel,
      isSystemSettingsOpen: $.isSystemSettingsOpen,
      isUserSettingsOpen: $.isSettingsModalOpen,
      memberListCollapsed: $.memberPanelCollapsed,
      memberListWidth: $.memberPanelWidth,
      activeMemberProfile: $.activeMemberProfile,
      membersForMemberList: $.memberListUsers,
      toggleMemberList: $.toggleMemberList,
    },
    voiceScreenShare: {
      vcVideo: $.vcVideo,
      vcScreenshare: $.vcScreenshare,
      isScreenSharePickerOpen: $.isScreenSharePickerOpen,
      isDesktopStreamingControlOpen: $.isDesktopStreamingControlOpen,
      desktopStreamingControlMode: $.desktopStreamingControlMode,
      desktopStreamingPreferences: $.desktopStreamingPreferences,
      setDesktopStreamingPreferences: $.setDesktopStreamingPreferences,
      startVcScreenShare: $.startVcScreenShare,
      startDesktopScreenShare: $.startDesktopScreenShare,
      startDesktopCameraStream: $.startDesktopCameraStream,
      onDesktopCameraStarted: $.onDesktopCameraStarted,
      stopVcScreenShare: $.stopVcScreenShare,
    },
    voice: {
      getVcActivityPresenceForUser: $.getVcActivityPresenceForUser,
      getVcChannelActivityPresenceForChannel:
        $.getVcChannelActivityPresenceForChannel,
      effectiveVcActivityKingUserId: $.effectiveVcActivityKingUserId,
      vcHangmanActivity: $.vcHangmanActivity,
      hangmanRosterUserIds: $.hangmanRosterUserIds,
      hangmanGameRoomConnected: $.hangmanGameRoomConnected,
      hangmanGameRoomLastError: $.hangmanGameRoomLastError,
      vcSkrigglesActivity: $.vcSkrigglesActivity,
      skrigglesRosterUserIds: $.skrigglesRosterUserIds,
      skrigglesCanvasEvents: $.skrigglesCanvasEvents,
      vcCodenamesActivity: $.vcCodenamesActivity,
      codenamesRosterUserIds: $.codenamesRosterUserIds,
      vcCodenamesSpymasterKey: $.vcCodenamesSpymasterKey,
      commitVcHangmanWord: $.commitVcHangmanWord,
      requestVcHangmanGuessLetter: $.requestVcHangmanGuessLetter,
      requestVcHangmanNextRound: $.requestVcHangmanNextRound,
      wordlineView: $.wordlineView,
      submitWordlineGuess: $.submitWordlineGuess,
      setWordlineMode: $.setWordlineMode,
      commitSkrigglesWordChoice: $.commitSkrigglesWordChoice,
      submitSkrigglesGuess: $.submitSkrigglesGuess,
      updateSkrigglesSettings: $.updateSkrigglesSettings,
      startSkrigglesGame: $.startSkrigglesGame,
      advanceSkrigglesRound: $.advanceSkrigglesRound,
      publishSkrigglesStrokeBatch: $.publishSkrigglesStrokeBatch,
      publishSkrigglesCanvasCmd: $.publishSkrigglesCanvasCmd,
      publishSkrigglesCanvasSnapshot: $.publishSkrigglesCanvasSnapshot,
      tickSkrigglesTimers: $.tickSkrigglesTimers,
      vcTicTacToeActivity: $.vcTicTacToeActivity,
      vcTicTacToePendingInvite: $.vcTicTacToePendingInvite,
      sendVcTicTacToeChallenge: $.sendVcTicTacToeChallenge,
      respondVcTicTacToeInvite: $.respondVcTicTacToeInvite,
      dismissVcTicTacToeInvite: $.dismissVcTicTacToeInvite,
      requestVcTicTacToeMove: $.requestVcTicTacToeMove,
      requestVcTicTacToeRematch: $.requestVcTicTacToeRematch,
      commitVcCodenamesDeal: $.commitVcCodenamesDeal,
      requestVcCodenamesSetup: $.requestVcCodenamesSetup,
      requestVcCodenamesClue: $.requestVcCodenamesClue,
      requestVcCodenamesReveal: $.requestVcCodenamesReveal,
      requestVcCodenamesEndTurn: $.requestVcCodenamesEndTurn,
      requestVcCodenamesNewGame: $.requestVcCodenamesNewGame,
      requestVcCodenamesPushKeyToOrchestrator:
        $.requestVcCodenamesPushKeyToOrchestrator,
      activeVoiceChannelParticipants: $.activeVoiceChannelParticipants,
      liveKitState: $.liveKitState,
      liveKitNetworkStats: $.liveKitNetworkStats,
      liveKitRoom: $.liveKitRoom,
      vcRemoteParticipants: $.vcRemoteParticipants,
      vcMirrorCamera: $.vcMirrorCamera,
      switchVcCamera: $.switchVcCamera,
      setVcVideoQuality: $.setVcVideoQuality,
      speakingMap: $.speakingMap,
      localSpeaking: $.localSpeaking,
      localAudioLevel: $.localAudioLevel,
      switchMicDevice: $.switchMicDevice,
      switchSpeakerDevice: $.switchSpeakerDevice,
      setLkOutputVolume: $.setLkOutputVolume,
      reapplyVoiceProcessing: $.reapplyVoiceProcessing,
      setMicTestListenDeafen: $.setMicTestListenDeafen,
      currentVoiceChannelId: $.currentVoiceChannelId,
      currentVoiceChannelName: $.currentVoiceChannelName,
      dmCallDeafened: $.dmCallDeafened,
      dmCallFullscreen: $.dmCallFullscreen,
      dmCallMuted: $.dmCallMuted,
      dmCallQuarterView: $.dmCallQuarterView,
      dmCallMatchesActiveChannel: $.dmCallMatchesActiveChannel,
      activeDmThreadCallUi: $.activeDmThreadCallUi,
      dmCallVideo: $.dmCallVideo,
      dmCallScreenshare: $.dmCallScreenshare,
      dmCallCallViewParticipants: $.dmCallCallViewParticipants,
      dmCallWithUserId: $.dmCallWithUserId,
      dmCallRinging: $.dmCallRinging,
      dmCallAwaitingAccept: $.dmCallAwaitingAccept,
      dmCallIncoming: $.dmCallIncoming,
      dmCallRingRemoteVanishing: $.dmCallRingRemoteVanishing,
      dmCallGlassPeer: $.dmCallGlassPeer,
      dmCallVoiceStripThreadId: $.dmCallVoiceStripThreadId,
      dmCallVoiceStripTitle: $.dmCallVoiceStripTitle,
      channelPanelVoiceChannelId: $.channelPanelVoiceChannelId,
      channelPanelVoiceChannelName: $.channelPanelVoiceChannelName,
      channelPanelVcMutedEffective: $.channelPanelVcMutedEffective,
      channelPanelVcDeafenedEffective: $.channelPanelVcDeafenedEffective,
      channelPanelVcVideoEffective: $.channelPanelVcVideoEffective,
      channelPanelVcScreenshareEffective: $.channelPanelVcScreenshareEffective,
      onChannelPanelVcMuted: $.onChannelPanelVcMuted,
      onChannelPanelVcDeafened: $.onChannelPanelVcDeafened,
      onChannelPanelVcVideo: $.onChannelPanelVcVideo,
      onChannelPanelVcScreenshare: $.onChannelPanelVcScreenshare,
      onGuildChannelVcMuted: $.onGuildChannelVcMuted,
      onGuildChannelVcDeafened: $.onGuildChannelVcDeafened,
      onGuildChannelVcVideo: $.onGuildChannelVcVideo,
      onGuildChannelVcScreenshare: $.onGuildChannelVcScreenshare,
      onDmCallVcMuted: $.onDmCallVcMuted,
      onDmCallVcDeafened: $.onDmCallVcDeafened,
      onDmCallVcVideo: $.onDmCallVcVideo,
      onDmCallVcScreenshare: $.onDmCallVcScreenshare,
      applyDmCallDeafened: $.applyDmCallDeafened,
      toggleDmCallMuted: $.toggleDmCallMuted,
      handleJoinVoice: $.handleJoinVoiceNavigation,
      handleJoinVoiceIfAllowed: $.handleJoinVoiceNavigation,
      handleLeaveVoice: $.handleLeaveVoiceNavigation,
      handleChannelVoicePanelLeave: $.handleChannelVoicePanelLeave,
      onJoinVoice: $.onJoinVoice,
      onJoinVoiceUi: $.onJoinVoice,
      onLeaveVoice: $.onLeaveVoice,
      onLeaveVoiceUi: $.onLeaveVoice,
      onVcChatButtonClick: $.onVcChatButtonClickNavigation,
      handleMinimizeVoiceView: $.handleMinimizeVoiceViewNavigation,
      isViewingVoiceChannel: $.isViewingVoiceChannel,
      isScreenSharePickerOpen: $.isScreenSharePickerOpen,
      isDesktopStreamingControlOpen: $.isDesktopStreamingControlOpen,
      desktopStreamingControlMode: $.desktopStreamingControlMode,
      desktopStreamingPreferences: $.desktopStreamingPreferences,
      fullscreenStreamParticipantId: $.fullscreenStreamParticipantId,
      vcActivityUi: $.vcActivityUi,
      openVcActivityPicker: $.openVcActivityPickerOnVoice,
      openVcActivityYoutubeBrowse: $.openVcActivityYoutubeBrowseOnVoice,
      openVcActivityWatchTogether: $.openVcActivityWatchTogetherOnVoice,
      openVcActivityWordle: $.openVcActivityWordleOnVoice,
      openVcActivityHangman: $.openVcActivityHangmanOnVoice,
      openVcActivitySkriggles: $.openVcActivitySkrigglesOnVoice,
      openVcActivityTicTacToe: $.openVcActivityTicTacToeOnVoice,
      openVcActivityOpenGuessr: $.openVcActivityOpenGuessrOnVoice,
      openVcActivitySkribblIo: $.openVcActivitySkribblIoOnVoice,
      openVcActivityGarticPhone: $.openVcActivityGarticPhoneOnVoice,
      openVcActivityKrunker: $.openVcActivityKrunkerOnVoice,
      openVcActivityCodenames: $.openVcActivityCodenamesOnVoice,
      openVcActivityRichup: $.openVcActivityRichupOnVoice,
      openVcActivityGooberDash: $.openVcActivityGooberDashOnVoice,
      openVcActivitySmashKarts: $.openVcActivitySmashKartsOnVoice,
      openVcActivityClusterRush: $.openVcActivityClusterRushOnVoice,
      setVcActivityYoutubeVideo: $.setVcActivityYoutubeVideo,
      setVcYoutubeBrowseOpen: $.setVcYoutubeBrowseOpen,
      addVcYoutubeToQueue: $.addVcYoutubeToQueue,
      removeVcYoutubeFromQueue: $.removeVcYoutubeFromQueue,
      moveVcYoutubeInQueue: $.moveVcYoutubeInQueue,
      playVcYoutubeAtIndex: $.playVcYoutubeAtIndex,
      playVcYoutubeNext: $.playVcYoutubeNext,
      playVcYoutubePrevious: $.playVcYoutubePrevious,
      setWatchTogetherLobbyRole: $.setWatchTogetherLobbyRole,
      ensureWatchTogetherSessionId: $.ensureWatchTogetherSessionId,
      patchWatchTogetherUi: $.patchWatchTogetherUi,
      setWatchTogetherBrowseOpen: $.setWatchTogetherBrowseOpen,
      startWatchTogetherSession: $.startWatchTogetherSession,
      playWatchTogetherAtIndex: $.playWatchTogetherAtIndex,
      closeVcActivity: $.closeVcActivity,
      vcYoutubeRemotePlayback: $.vcYoutubeRemotePlayback,
      publishVcYoutubePlaybackSync: $.publishVcYoutubePlaybackSync,
      vcYoutubePlaybackShouldPublish: $.vcYoutubePlaybackShouldPublish,
      vcWatchTogetherRemotePlayback: $.vcWatchTogetherRemotePlayback,
      publishVcWatchTogetherPlaybackSync: $.publishVcWatchTogetherPlaybackSync,
      vcWatchTogetherPlaybackShouldPublish:
        $.vcWatchTogetherPlaybackShouldPublish,
      getLocalScreenTrack: $.getVcLocalScreenTrack,
      getLocalCameraTrack: $.getVcLocalCameraTrack,
      getRemoteParticipantVolume: $.getRemoteParticipantVolume,
      setRemoteParticipantVolume: $.setRemoteParticipantVolume,
      vcDeafened: $.vcDeafened,
      applyVcDeafened: $.applyVcDeafened,
      applyVcMuted: $.applyVcMuted,
      vcMuted: $.vcMuted,
      vcScreenshare: $.vcScreenshare,
      vcVideo: $.vcVideo,
      isVcActive: $.isVcActive,
      isVcConnected: $.isVcConnected,
      isVcConnecting: $.isVcConnecting,
      isVcDisconnecting: $.isVcDisconnecting,
      joinVoiceChannel: $.joinVoiceChannel,
      leaveVoiceChannel: $.leaveVoiceChannel,
    },
    messaging: {
      handleGoToChannel: $.messageActions.handleGoToChannel,
      handleGoToMessage: $.messageActions.handleGoToMessage,
      handlePollVote: $.messageActions.handlePollVote,
      handleReact: $.messageActions.handleReact,
      pinMessage: $.pinMessage,
      toggleReaction: $.toggleReactionOnMessages,
      votePoll: $.messageActions.handlePollVote,
      recordReaction: $.reactionFavorites.recordReaction,
      removeReactionFavorite: $.reactionFavorites.removeReactionFavorite,
      topReactions: $.reactionFavorites.topReactions,
      goToPinnedMessage: $.goToPinnedMessage,
      goToSearchPage: $.goToSearchPage,
      searchError: $.searchError,
      searchLoading: $.searchLoading,
      searchResultMessages: $.searchResultMessages,
      searchResultPage: $.searchResultPage,
      searchScopeHint: $.searchScopeHint,
      searchText: $.searchText,
      paginatedSearchResults: $.paginatedSearchResults,
      totalPages: $.totalPages,
      onSearchInput: $.onSearchInput,
      clearSearch: $.clearSearch,
      forwardModalOpen: $.forwardModalOpen,
      forwardPickerDestinations: $.forwardPickerDestinations,
      forwardModalSourceSummary: $.forwardModalSourceSummary,
      openForwardMessagePicker: $.openForwardMessagePicker,
      closeForwardMessagePicker: $.closeForwardMessagePicker,
      submitForwardedMessage: $.submitForwardedMessage,
      socketSendMessage: $.socketSendMessage,
      sendMessage: $.sendMessage,
      searchActiveTab: $.searchActiveTab,
      searchFilter: $.searchFilter,
      searchIsLoading: $.searchIsLoading,
      searchResults: $.searchResults,
      searchStatus: $.searchStatus,
    },
    serverChromeCallbacks: {
      isServerSettingsModalOpen: $.isServerSettingsModalOpen,
      serverSettingsModalInitialSection: $.serverSettingsModalInitialSection,
      serverSettingsModalActiveSection: $.serverSettingsModalActiveSection,
      isInviteModalOpen: $.isInviteModalOpen,
      clearInviteVoiceContext: () => {
        $.inviteModalVoiceChannelId.value = null;
        $.inviteModalVoiceChannelName.value = null;
      },
      canOpenInviteForServer: $.canOpenInviteForServer,
      canOpenServerSettingsForServer: $.canOpenServerSettingsForServer,
    },
    serverRail: {
      handleServerRailInvite: $.handleServerRailInvite,
      handleServerRailMarkRead: $.handleServerRailMarkRead,
      handleServerRailMarkAllRead: $.handleServerRailMarkAllRead,
      handleDmRailMarkAllRead: $.handleDmRailMarkAllRead,
      handleChannelMarkRead: $.handleChannelMarkRead,
      handleServerRailLeave: $.handleServerRailLeave,
      handleServerRailNotificationSettings:
        $.handleServerRailNotificationSettings,
      handleServerRailSettings: $.handleServerRailSettings,
      openServerFromMore: $.openServerFromMore,
      openServerSettingsFromUrl: $.openServerSettingsFromUrl,
      selectedServerId: useComputedRefAlias($.selectedServerIdRef),
      servers: useComputedRefAlias($.serverRowsRef),
      onLeaveServerModalUpdate: $.onLeaveServerModalUpdate,
      confirmLeaveServerFromModal: $.confirmLeaveServerFromModal,
      isLeaveServerModalOpen: $.isLeaveServerModalOpenRef,
      leaveServerModalServerName: $.leaveServerModalServerNameRef,
      leaveServerModalVariant: $.leaveServerModalVariantRef,
      openServerNotificationSettings: $.openServerNotificationSettings,
      handleServerNotificationSave: $.handleServerNotificationSave,
      serverNotificationLevelsMap: $.serverNotificationLevelsMap,
      serverPingKindByServerId: $.serverPingKindByServerId,
      serverPingBubbleByServerId: $.serverPingBubbleByServerId,
      serverPingChannelDotsByServerId: $.serverPingChannelDotsByServerId,
      serverUnreadActivityDotByServerId: $.serverUnreadActivityDotByServerId,
      channelMissedActivityByChannelId: $.channelMissedActivityByChannelId,
      currentServerNotificationLevel: $.currentServerNotificationLevel,
      isServerNotificationSettingsOpen: $.isServerNotificationSettingsOpen,
      canDeleteCurrentServer: $.canDeleteCurrentServerComputed,
      canOpenServerSettings: $.roleUi.canOpenServerSettings,
      canOpenServerSettingsForServer: $.roleUi.canOpenServerSettingsForServer,
      canOpenInviteForServer: $.canOpenInviteForServer,
      reorderVisibleServers: $.serverStore.reorderVisibleServers,
      syncVanityAcrossServerLists: $.syncVanityAcrossServerLists,
      isServerUnread: $.isServerUnread,
      onOpenCreateChannel: $.openCreateChannelOnServer,
      hasGuildChannelChrome: $.hasGuildChannelChrome,
    },
    shellLayout: {
      toggleChannelPanel: $.toggleChannelPanel,
      openDMPanel: $.selectDMTab,
    },
    dmGroupFriendsInput: {
      currentUserId: $.currentUserIdForSocket,
      users: $.workspace.users,
      friendIds: $.workspace.friendIds,
    },
    dm: {
      echoDmPeerByChannelId: $.echoDmPeerByChannelId,
      echoDmThreadIds: $.echoDmThreadIds,
      echoBlockedUserIds: $.echoBlockedUserIds,
      dmIncomingRailCluster: $.dmIncomingRailCluster,
      selectMessageRequest: $.selectMessageRequest,
      ignoreMessageRequest: $.ignoreMessageRequest,
      returnFromMessageRequests: $.returnFromMessageRequests,
      acceptFriendRequest: $.acceptFriendRequest,
      declineFriendRequest: $.declineFriendRequest,
      cancelFriendRequest: $.cancelFriendRequest,
      sendFriendRequest: $.sendFriendRequest,
      handleDmMarkRead: $.handleDmMarkRead,
      hideDmFromInboxUser: $.hideDmFromInboxUser,
      hideDmFromInboxGroup: $.hideDmFromInboxGroup,
      isDmInboxUserFavorite: $.isDmInboxUserFavorite,
      isDmInboxGroupFavorite: $.isDmInboxGroupFavorite,
      toggleFavoriteDmInbox: $.toggleFavoriteDmInbox,
      handleAcceptMessageRequest: $.handleAcceptMessageRequest,
      dmInboxEntriesForPanel: $.dmInboxEntriesForPanel,
      dmUsersForDmPanel: $.dmUsersForDmPanelComputed,
      groupDMListForPanel: $.groupDMListForPanelComputed,
      isEchoUserFriend: $.friendshipQueries.isEchoUserFriend,
      isEchoUserIncomingFriendRequest:
        $.friendshipQueries.isEchoUserIncomingFriendRequest,
      isEchoUserOutgoingFriendRequest:
        $.friendshipQueries.isEchoUserOutgoingFriendRequest,
      selectIncomingDmFromRail: $.selectIncomingDmFromRail,
      selectIncomingGroupDmFromRail: $.selectIncomingGroupDmFromRail,
      openDmInboxFromRailOverflow: $.openDmInboxFromRailOverflow,
      groupDMs: $.groupDMs,
      groupDMPreselectedIds: $.groupDMPreselectedIds,
      groupDMLockedIds: $.groupDMLockedIds,
      groupDmMaxMembers: $.groupDmMaxMembers,
      dmActiveTab: $.dmActiveTab,
      dmPanelWidth: $.dmPanelWidth,
      startDmPanelResize: $.startDmPanelResize,
      dmPartnerUser: $.dmPartnerUser,
      guestFriendsLocked: $.guestFriendsLocked,
      handleCreateGroupDM: $.groupDmActions.handleCreateGroupDM,
      handleKickGroupDmMember: $.handleKickGroupDmMember,
      handleLeaveGroupDm: $.handleLeaveGroupDm,
      onRemoveGroupDmMember: $.handleKickGroupDmMember,
      onLeaveGroupDm: $.handleLeaveGroupDm,
      onOpenAddMembersToGroupDm: $.onOpenAddMembersToGroupDm,
      handleSelectGroupDM: $.handleSelectGroupDMWithGuestGuard,
      handleUpdateGroupFromSettings:
        $.groupDmActions.handleUpdateGroupFromSettings,
      openGroupDMModal: $.groupDmActions.openGroupDMModal,
      openGroupOverviewPanel: $.groupDmActions.openGroupOverviewPanel,
      openGroupSettingsFromHeader: $.groupDmActions.openGroupSettingsFromHeader,
      groupSettingsMembers: $.groupSettingsMembers,
      groupSettingsId: $.groupSettingsId,
      isGroupDM: $.isGroupDMComputed,
      isGroupDMModalOpen: $.isGroupDMModalOpen,
      isGroupDMSettingsOpen: $.isGroupDMSettingsOpen,
      groupDmSettingsInitialFocus: $.groupDmSettingsInitialFocus,
      activeGroupSettingsId: $.activeGroupSettingsId,
      isGroupOverviewOpen: $.isGroupOverviewOpen,
    },
    moderation: {
      canModerateMemberInServer: $.canModerateMemberInServer,
      canVcModerateMember: $.canVcModerateMember,
      canModerateMemberActionInServer: $.canModerateMemberActionInServer,
      canChangeMemberNicknameInServer: $.canChangeMemberNicknameInServer,
      canModerateMessageAuthor: $.canModerateMessageAuthorForSurface,
      moderationModalOpen: $.moderationModalOpen,
      moderationAction: $.moderationAction,
      moderationTargetUserId: $.moderationTargetUserId,
      moderationTargetUser: $.moderationTargetUser,
      handleModerateUser: $.handleModerateUser,
      onModerationModalConfirm: $.onModerationModalConfirm,
      handleVcModerate: $.handleVcModerate,
    },
    shellChrome: {
      ExploreView: $.ExploreView,
      MORE_SERVERS_PANEL_WIDTH: $.gridMoreServersPanelWidth,
      MORE_SERVERS_COMPACT_WIDTH: $.gridMoreServersCompactWidth,
      DM_PANEL_WIDTH: 240,
      appGridTemplateColumns: $.appGridTemplateColumns,
      expandChannels: $.expandChannels,
      exploreDiscoverableServers: $.exploreDiscoverableServers,
      isExploreView: $.isExploreView,
      welcomeBackExploreGate: $.welcomeBackExploreGate,
      welcomeBackExploreMemberEmptyDirectory:
        $.welcomeBackExploreMemberEmptyDirectory,
      showWelcomeBackSlimBanner: $.showWelcomeBackSlimBanner,
      inviteLandingActive: $.inviteLanding.inviteLandingActive,
      inviteLandingPreview: $.inviteLanding.invitePreview,
      inviteLandingLoading: $.inviteLanding.isLoading,
      inviteLandingError: $.inviteLanding.previewError,
      inviteLandingPersistBeforeOAuth: $.inviteLanding.persistInviteBeforeOAuth,
      showNsfwChatGate: $.showNsfwChatGate,
      acknowledgeNsfwChannel: $.acknowledgeNsfwChannel,
      declineNsfwGate: $.declineNsfwGate,
      mainContentColumns: $.mainContentColumns,
      mainContentColumnsEffective: $.mainContentColumnsEffective,
      addServerInitialView: $.addServerInitialView,
      addServerJoinError: $.addServerJoinError,
      addServerCreateBusy: $.addServerCreateBusy,
      addServerJoinBusy: $.addServerJoinBusy,
      addServerJoinInvitePrefill: $.addServerJoinInvitePrefill,
      exploreDirectoryJoinBusy: $.exploreDirectoryJoinBusy,
      joinEchoServerWithInviteRaw: $.joinEchoServerWithInviteRaw,
      handleJoinWithInviteLink: $.handleJoinWithInviteLink,
      handleCreateServer: $.handleCreateServer,
      handleJoinDiscoverableServer: $.handleJoinDiscoverableServer,
      isServerEmptyOnboarding: $.isServerEmptyOnboarding,
      isJoinServerConfirmModalOpen: $.isJoinServerConfirmModalOpenRef,
      joinServerConfirmPreview: $.joinServerConfirmPreviewRef,
      joinServerConfirmBusy: $.joinServerConfirmBusyRef,
      confirmJoinServerFromModal: $.confirmJoinServerFromModal,
      onJoinServerConfirmModalUpdate: $.onJoinServerConfirmModalUpdate,
      isServerApplicationModalOpen: $.isServerApplicationModalOpenRef,
      serverApplicationPayload: $.serverApplicationPayloadRef,
      serverApplicationBusy: $.serverApplicationBusyRef,
      onServerApplicationModalUpdate: $.onServerApplicationModalUpdate,
      confirmServerApplicationSubmittedFromModal:
        $.confirmServerApplicationSubmittedFromModal,
    },
    previewCanModerateMembers: {
      previewCanModerateMembers: () => $.roleUi.previewCanModerateMembers(),
    },
    core: {
      activeChannel: $.effectiveActiveChannel,
      activeChannelContext: $.activeChannelContext,
      activeChannelId: $.activeChannelId,
      activeChannelMessages: $.activeChannelMessages,
      activeChannelMessagesMap: $.activeChannelMessagesMap,
      linkedDiscordUserId: $.linkedDiscordUserId,
      linkedDiscordState: $.linkedDiscordState,
      activeGroupCallMembers: $.activeGroupCallMembersVisible,
      activeGroupDM: $.activeGroupDM,
      activeMemberProfile: $.activeMemberProfile,
      activeRailTab: $.activeRailTab,
      addFilter: $.addFilter,
      allChannels: $.allChannels,
      applyEchoPresenceFromSocket: $.applyEchoPresenceFromSocket,
      authModalInitialLoginEntry: $.authModalInitialLoginEntry,
      authModalPasskeyOnOpen: $.authModalPasskeyOnOpen,
      authModalInitialTab: $.authModalInitialTab,
      authModalInitialSubView: $.authModalInitialSubView,
      authSession: $.authSession,
      callOverlay: $.callOverlay,
      canCreateChannels: $.canCreateChannels,
      canManageThisChannel: $.canManageThisChannel,
      canInviteToCurrentServer: $.canInviteToCurrentServer,
      canJoinPreviewVoiceChannel: $.canJoinPreviewVoiceChannel,
      categoriesForServer: $.categoriesForServer,
      categorySettingsTarget: $.categorySettingsTarget,
      categorySettingsEchoPermissionEditor:
        $.categorySettingsEchoPermissionEditor,
      channelPanelCollapsed: $.channelPanelCollapsed,
      channelPanelBubbleMode: $.channelPanelBubbleMode,
      channelPanelWidth: $.channelPanelWidth,
      channelSettingsCategoryPermissionDefaults:
        $.channelSettingsCategoryPermissionDefaults,
      channelSettingsCategoryAutoDeleteAfterSeconds:
        $.channelSettingsCategoryAutoDeleteAfterSeconds,
      channelSettingsEchoPermissionEditor:
        $.channelSettingsEchoPermissionEditor,
      channelSettingsTarget: $.channelSettingsTarget,
      clearRolePreview: $.roleUi.clearRolePreview,
      closeDMPanel: $.closeDMPanel,
      clearPhoneHomeDmThread: $.clearPhoneHomeDmThread,
      closePinsDropdown: $.closePinsDropdown,
      createChannelCategoryNames: $.createChannelCategoryNames,
      createChannelCategoryOptions: $.createChannelCategoryOptions,
      createChannelInitialCategoryId: $.createChannelInitialCategoryId,
      currentUser: $.currentUser,
      customStatus: $.customStatus,
      deleteMessage: $.messageActions.deleteMessage,
      deleteMessageCore: $.messageActions.deleteMessage,
      ...$.echoCanContext,
      echoChannelHistory: $.echoChannelHistory,
      echoRoleCatalog: $.roleUi.echoRoleCatalog,
      echoWorkspaceError: $.echoWorkspaceError,
      editMessage: $.messageActions.editMessage,
      fillImageSlot: $.messageActions.fillImageSlot,
      effectiveActiveChannel: $.effectiveActiveChannel,
      endDmCall: $.endDmCall,
      leaveDmCallVoice: $.leaveDmCallVoice,
      rejoinDmCallVoice: $.rejoinDmCallVoice,
      answerDmCall: $.answerDmCall,
      declineDmCall: $.declineDmCall,
      dmCallRingUi: $.dmCallRingUi,
      dmCallLobbyAfterSelfLeave: $.dmCallLobbyAfterSelfLeave,
      compactPagerPane: $.compactPagerPane,
      compactGuildTriPaneChannelPanelOpen:
        $.compactGuildTriPaneChannelPanelOpen,
      isCompactPhoneShell: $.isCompactPhoneShell,
      useCompactPhoneTabShell: $.useCompactPhoneTabShell,
      mobileBottomTab: $.mobileBottomTab,
      mobileHomeStack: $.mobileHomeStack,
      mobileServersStack: $.mobileServersStack,
      mobileChannelSheetOpen: $.mobileChannelSheetOpen,
      mobileMembersOverlayOpen: $.mobileMembersOverlayOpen,
      guildMobileVcLobby: $.guildMobileVcLobby,
      openGuildMobileVcLobby: $.openGuildMobileVcLobby,
      closeGuildMobileVcLobby: $.closeGuildMobileVcLobby,
      collapseMembers: $.collapseMembers,
      expandMembers: $.expandMembers,
      expandVoiceSideChat: $.expandVoiceSideChat,
      expandedProfile: $.expandedProfile,
      filterChips: $.filterChips,
      findChannelContextById: $.findChannelContextById,
      getChannelDisplayName,
      getChannelIcon: $.channelIconResolver.getIconUrl,
      getFirstTextChannelId: $.getFirstTextChannelId,
      getLatestDMUserId: $.messageActions.getLatestDMUserId,
      getServerChannelInfoForMainSurface: $.getServerChannelInfoForMainSurface,
      handleActiveChannelChange: $.handleActiveChannelChangeNavigation,
      handleChangeMemberNicknameFromMemberList:
        $.handleChangeMemberNicknameFromMemberList,
      handleCategoryDelete: $.handleCategoryDelete,
      handleCategoryReorder: $.handleCategoryReorder,
      handleCategorySettingsSave: $.handleCategorySettingsSave,
      handleChannelDelete: $.handleChannelDelete,
      handleChannelReorder: $.handleChannelReorder,
      handleChannelSettingsSave: $.handleChannelSettingsSave,
      deleteChannelById: $.deleteChannelById,
      deleteCategoryById: $.deleteCategoryById,
      handleCreateCategorySubmit: $.handleCreateCategorySubmit,
      handleCreateChannelModalSubmit: $.handleCreateChannelModalSubmit,
      handleCreateChannelSubmit: $.handleCreateChannelSubmit,
      handleExpandedProfileOpenServer: $.handleExpandedProfileOpenServer,
      handleExpandedProfileAcceptIncomingFriendRequest:
        $.handleExpandedProfileAcceptIncomingFriendRequest,
      handleExpandedProfileDeclineIncomingFriendRequest:
        $.handleExpandedProfileDeclineIncomingFriendRequest,
      appActionRegistry: $.appActionRegistry,
      appLayoutActions: $.appLayoutActions,
      chatMessageNavBridge: $.chatMessageNavBridge,
      handleInviteFriend: $.handleInviteFriend,
      handlePinMessage: $.pinToggleHandlers.handlePinMessage,
      handleServerDeleted: $.handleServerDeleted,
      handleStartRolePreview: $.roleUi.startRolePreview,
      handleUnpinMessage: $.pinToggleHandlers.handleUnpinMessage,
      handleUpdateCustomStatus: $._handleUpdateCustomStatus,
      hydrateEchoFromApi: $.hydrateEchoFromApi,
      icons,
      inviteLinkForServer: $.inviteLinkForServer,
      inviteLinkFromApi: $.inviteLinkFromApi,
      inviteLinkLookupPending: $.inviteLinkLookupPending,
      inviteLinkFromSelectedServer: $.inviteLinkFromSelectedServer,
      inviteApplicationsEnabled: $.inviteApplicationsEnabled,
      inviteJoinLinksEnabled: $.inviteJoinLinksEnabled,
      inviteCanCreateDirectHexInvite: $.inviteCanCreateDirectHexInvite,
      directHexInviteLink: $.directHexInviteLink,
      directHexInviteBusy: $.directHexInviteBusy,
      createDirectHexInvite: $.createDirectHexInvite,
      inviteableFriends: $.inviteableFriends,
      isAddServerModalOpen: $.isAddServerModalOpen,
      isInviteModalOpen: $.isInviteModalOpen,
      inviteModalVoiceChannelId: $.inviteModalVoiceChannelId,
      inviteModalVoiceChannelName: $.inviteModalVoiceChannelName,
      isAuthModalOpen: $.isAuthModalOpen,
      isAuthenticated: $.isAuthenticatedComputed,
      isChannelActive: $.isChannelActive,
      isCompactShell: $.isCompactShell,
      isCompactGuildSplitShell: $.isCompactGuildSplitShell,
      isCreateCategoryModalOpen: $.isCreateCategoryModalOpen,
      isCreateChannelModalOpen: $.isCreateChannelModalOpen,
      isDmUiContext: $.isDmUiContext,
      isDMPanelOpen: $.isDMPanelOpen,
      isEchoGraphId,
      isEchoUserBlocked: $.isEchoUserBlocked,
      isExpandedProfileModalOpen: $.isExpandedProfileModalOpen,
      isExpandedProfileSidePanel: $.isExpandedProfileSidePanel,
      isGuest: $.isGuest,
      isGuestCaptchaModalOpen: $.isGuestCaptchaModalOpen,
      isGuestDisplayNameModalOpen: $.isGuestDisplayNameModalOpen,
      isGuestWelcomePrefsModalOpen: $.isGuestWelcomePrefsModalOpen,
      isGuestUpgradeModalOpen: $.isGuestUpgradeModalOpen,
      isInDMChat: $.isInDmThreadOrIdleMainSurface,
      isInDMMode: $.isInDMModeComputed,
      isMemberPopoutOpen: $.isMemberPopoutOpen,
      isMemberProfileOpen: useComputedRefAlias($.isMemberPopoutOpen),
      isMoreServersCompact: $.isMoreServersCompact,
      isMoreServersPanelOpen: $.isMoreServersPanelOpen,
      isMoreServersPinned: $.isMoreServersPinned,
      isChannelPanelSwitchLoading: $.isChannelPanelSwitchLoading,
      isChannelTreeLoadedForSelectedServer:
        $.isChannelTreeLoadedForSelectedServer,
      isGuildShellSettling: $.isGuildShellSettling,
      isMessageSurfaceSwitchLoading: $.isMessageSurfaceSwitchLoading,
      isMemberSurfaceSwitchLoading: $.isMemberSurfaceSwitchLoading,
      isEchoRoleBootstrapLoading: $.isEchoRoleBootstrapLoading,
      isPinsDropdownOpen: $.isPinsDropdownOpen,
      isRolePreviewActiveForServer: $.roleUi.isRolePreviewActiveForServer,
      isSearchActive: $.isSearchActive,
      isSelfProfilePopoutOpen: $.isSelfProfilePopoutOpen,
      isServerSettingsModalOpen: $.isServerSettingsModalOpen,
      isSettingsModalOpen: $.isSettingsModalOpen,
      settingsModalInitialSection: $.settingsModalInitialSection,
      settingsModalActiveSection: $.settingsModalActiveSection,
      serverSettingsModalInitialSection: $.serverSettingsModalInitialSection,
      serverSettingsModalActiveSection: $.serverSettingsModalActiveSection,
      mainSurface: $.mainSurface,
      markActiveChannelAsRead: $.markActiveChannelAsRead,
      memberListResolveHighestRole: $.resolveMemberHighestRole,
      memberListRoleManagement: $.roleUi.memberListRoleManagement,
      memberPopoutOpenRolesPanel: $.memberPopoutOpenRolesPanel,
      memberPanelCollapsed: $.memberPanelCollapsed,
      memberListShowGuests: $.memberListShowGuests,
      memberPanelAutoCollapseUserOverride:
        $.memberPanelAutoCollapseUserOverride,
      markMemberPanelExpandedByUser: $.markMemberPanelExpandedByUser,
      markMemberPanelCollapsedByUser: $.markMemberPanelCollapsedByUser,
      memberPanelCollapsedEffective: $.memberPanelCollapsedEffective,
      memberPanelWidth: $.memberPanelWidth,
      memberPopoutAnchor: $.memberPopoutAnchor,
      workspace: $.workspace,
      presenceByUserId: $.presenceByUserId,
      presenceMobileByUserId: $.presenceMobileByUserId,
      newlyCreatedServerId: $.newlyCreatedServerId,
      onCategorySettingsModalOpenUpdate: $.onCategorySettingsModalOpenUpdate,
      onChannelSettingsModalOpenUpdate: $.onChannelSettingsModalOpenUpdate,
      continueAsGuest: $.continueAsGuest,
      onMemberPopoutOpenUpdate:
        $.memberPopoutChromeCallbacks.onMemberPopoutOpenUpdate,
      onGuestAccountUpgraded: $.onGuestAccountUpgraded,
      onGuestCaptchaVerified: $.onGuestCaptchaVerified,
      onUserSettingsModalUpdate:
        $.userSettingsModalCallbacks.onUserSettingsModalUpdate,
      onSettingsModalActiveSectionUpdate:
        $.userSettingsModalCallbacks.onSettingsModalActiveSectionUpdate,
      openCategorySettings: $.openCategorySettings,
      openChannelSettings: $.openChannelSettings,
      openCreateCategoryModal: $.openCreateCategoryModal,
      openCreateChannelModal: $.openCreateChannelModal,
      openGuestUpgradeModal: $.openGuestUpgradeModal,
      openServerSurface: $.openServerSurface,
      openUserSettingsModal: $.userSettingsModalCallbacks.openUserSettingsModal,
      openAddServerModal: $.openAddServerModal,
      openAuthModal: $.openAuthModal,
      openUserSettingsToDiscordFromAddServer:
        $.openUserSettingsToDiscordFromAddServer,
      pfpBarExpanded: $.pfpBarExpanded,
      pinPreview: $.pinPreview,
      pinnedMessageIdsForCurrentChannel: $.pinnedMessageIdsForCurrentChannel,
      pinnedMessagesForDropdown: $.pinnedMessagesForDropdown,
      pinsButtonRefDm: $.pinsButtonRefDm,
      pinsButtonRefServer: $.pinsButtonRefServer,
      pinsDropdownRect: $.pinsDropdownRect,
      previewHasUiPermission: $.roleUi.previewHasUiPermission,
      profileNotes: $.profileNotes,
      rawCategoriesForServer: $.rawCategoriesForServer,
      refreshEchoRoleData: $.refreshRoleData,
      removeFilter: $.removeFilter,
      resetChannelWidth: $.resetChannelWidth,
      resetDmPanelWidth: $.resetDmPanelWidth,
      resetMemberWidth: $.resetMemberWidth,
      resetVoiceSideChatWidth: $.resetVoiceSideChatWidth,
      resolvePreviewChannelPermission: $.resolvePreviewChannelPermission,
      rolePreview: $.roleUi.rolePreview,
      selectDM: $.selectDmUser,
      selectDMTab: $.selectDMTab,
      selectExploreTab: $.selectExploreTab,
      selectServersTab: $.selectServersTab,
      selectServersRailOnly: $.selectServersRailOnly,
      selectedDMUserId: $.selectedDMUserId,
      selectedMessageRequestId: $.selectedMessageRequestId,
      dmMentionNotifications: $.dmMentionNotifications,
      mentionNotificationHydrationLoading:
        $.mentionNotificationHydrationLoading,
      resolveDmMentionNotificationChannelLabel:
        $.resolveDmMentionNotificationChannelLabel,
      resolveDmMentionNotificationAuthorName:
        $.resolveDmMentionNotificationAuthorName,
      resolveDmMentionNotificationRowPreview:
        $.resolveDmMentionNotificationRowPreview,
      dmNotificationReadStateByChannelId: $.dmNotificationReadStateByChannelId,
      mentionNotificationCategoriesByServer:
        $.mentionNotificationCategoriesByServer,
      mentionNotificationServers: $.mentionNotificationServers,
      dmNotificationsReadPreset: $.dmNotificationsReadPreset,
      dmNotificationsSourceKey: $.dmNotificationsSourceKey,
      onOpenMentionNotification: $.onOpenMentionNotification,
      onMarkMentionNotificationRead: $.onMarkMentionNotificationRead,
      selectedServer: $.selectedServerView,
      selfProfile: $.selfProfile,
      selfProfileAnchor: $.selfProfileAnchor,
      serverSettingsCanManageRoles: $.roleUi.serverSettingsCanManageRoles,
      serverSettingsCanManageServer: $.roleUi.serverSettingsCanManageServer,
      serverStore: $.serverStore,
      sessionEndedMessage: $.sessionEndedMessage,
      discordBotExportReadyBanner: $.discordBotExportReadyBanner,
      dismissDiscordBotExportReadyBanner: $.dismissDiscordBotExportReadyBanner,
      shellNavState: $.shellNavState,
      startChannelResize: $.startChannelResize,
      startDmCall: $.startDmCall,
      startDmCallWithUserId: $.startDmCallWithUserId,
      startGroupCall: $.startGroupCall,
      startGroupCallWithId: $.startGroupCallWithId,
      startMemberResize: $.startMemberResize,
      startRolePreview: $.roleUi.startRolePreview,
      startVoiceSideChatResize: $.startVoiceSideChatResize,
      toggleMoreServersPanel: $.toggleMoreServersPanelChrome,
      togglePinsDropdown: $.togglePinsDropdown,
      toggleVoiceSideChat: $.toggleVoiceSideChat,
      toggleChannelPanelBubbleMode: $.toggleChannelPanelBubbleMode,
      voiceMobileSheetLevel: $.voiceMobileSheetLevel,
      bumpVoiceMobileChatFromCallScrollUp:
        $.bumpVoiceMobileChatFromCallScrollUp,
      bumpVoiceMobileChatFromCallScrollDown:
        $.bumpVoiceMobileChatFromCallScrollDown,
      narrowChannelPanelForActivityOverflowStep:
        $.narrowChannelPanelForActivityOverflowStep,
      unpinMessage: $.pinToggleHandlers.unpinMessage,
      updateCurrentUserStatus: $.updateStatusCast,
      voiceSideChatCollapsed: $.voiceSideChatCollapsed,
      voiceSideChatWidth: $.voiceSideChatWidth,
      watchActiveChannelWithServerChange: $.watchActiveChannelWithServerChange,
      isPersistedEchoDmThread: $.isPersistedEchoDmThread,
      workspaceReady: $.workspaceReady,
      onEchoMessageFailedGuest: $.onEchoMessageFailedGuest,
      dispatchNav: $.dispatchNav,
      echoCapabilitiesForServerId: $.echoCapabilitiesForServerId,
      liveChannelCapabilities: $.liveChannelCapabilities,
      refreshEchoSocialFromApi: $.refreshEchoSocialFromApi,
      guestCaptchaSiteKey: $.guestCaptchaSiteKey,
      submitPollVote: $.submitPollVoteViaSocket,
      submitReactionToggle: $.submitReactionToggle,
      submitPin: $.submitPinViaSocket,
      submitUnpin: $.submitUnpinViaSocket,
      submitMessageEdit: $.submitMessageEditViaSocket,
      submitMessageDelete: $.submitMessageDeleteViaSocket,
      showApiFetchErrorBanner: $.showApiFetchErrorBanner,
    },
  } as AssembleAppLayoutContextDeps;
}
