import type { AppLayoutControllerContext } from './appLayoutControllerTypes';

type DmSliceKeys =
  | 'echoDmPeerByChannelId'
  | 'echoDmThreadIds'
  | 'echoBlockedUserIds'
  | 'dmIncomingRailCluster'
  | 'selectMessageRequest'
  | 'ignoreMessageRequest'
  | 'returnFromMessageRequests'
  | 'acceptFriendRequest'
  | 'declineFriendRequest'
  | 'cancelFriendRequest'
  | 'sendFriendRequest'
  | 'handleDmMarkRead'
  | 'hideDmFromInboxUser'
  | 'hideDmFromInboxGroup'
  | 'isDmInboxUserFavorite'
  | 'isDmInboxGroupFavorite'
  | 'toggleFavoriteDmInbox'
  | 'handleAcceptMessageRequest'
  | 'dmGroupFriends'
  | 'dmInboxEntriesForPanel'
  | 'dmUsersForDmPanel'
  | 'groupDMListForPanel'
  | 'isEchoUserFriend'
  | 'isEchoUserIncomingFriendRequest'
  | 'isEchoUserOutgoingFriendRequest'
  | 'selectIncomingDmFromRail'
  | 'selectIncomingGroupDmFromRail'
  | 'openDmInboxFromRailOverflow'
  | 'groupDMs'
  | 'groupDMPreselectedIds'
  | 'groupDMLockedIds'
  | 'groupDmMaxMembers'
  | 'dmActiveTab'
  | 'dmPanelWidth'
  | 'startDmPanelResize'
  | 'dmPartnerUser'
  | 'guestFriendsLocked'
  | 'handleCreateGroupDM'
  | 'handleKickGroupDmMember'
  | 'handleLeaveGroupDm'
  | 'handleSelectGroupDM'
  | 'handleUpdateGroupFromSettings'
  | 'onRemoveGroupDmMember'
  | 'onLeaveGroupDm'
  | 'onOpenAddMembersToGroupDm'
  | 'groupSettingsMembers'
  | 'groupSettingsId'
  | 'openGroupDMModal'
  | 'openGroupOverviewPanel'
  | 'openGroupSettingsFromHeader'
  | 'isGroupDM'
  | 'isGroupDMModalOpen'
  | 'isGroupDMSettingsOpen'
  | 'groupDmSettingsInitialFocus'
  | 'activeGroupSettingsId'
  | 'isGroupOverviewOpen';

export function useAppLayoutContextDmSlice(
  deps: Pick<AppLayoutControllerContext, DmSliceKeys>,
) {
  const slice: Pick<AppLayoutControllerContext, DmSliceKeys> = { ...deps };
  return slice;
}
