import { computed, ref, shallowRef } from 'vue';
import { describe, expect, it, vi } from 'vitest';
import { useAppLayoutContextProfileSlice } from './useAppLayoutContextProfileSlice';
import { useAppLayoutContextVoiceSlice } from './useAppLayoutContextVoiceSlice';
import { useAppLayoutContextMessagingSlice } from './useAppLayoutContextMessagingSlice';
import { useAppLayoutContextServerRailSlice } from './useAppLayoutContextServerRailSlice';
import { useAppLayoutContextShellLayoutSlice } from './useAppLayoutContextShellLayoutSlice';
import { useAppLayoutContextDmSlice } from './useAppLayoutContextDmSlice';
import { useAppLayoutContextModerationSlice } from './useAppLayoutContextModerationSlice';
import { useAppLayoutContextShellChromeSlice } from './useAppLayoutContextShellChromeSlice';

describe('app layout context slices wiring', () => {
  it('profile slice preserves key delegates', () => {
    const openMemberProfile = vi.fn();
    const handleExpandedProfileOpenDM = vi.fn();
    const sendFriendRequest = vi.fn();
    const activeMemberProfile = ref<{ id: string } | null>(null);
    const slice = useAppLayoutContextProfileSlice({
      openMemberProfile: openMemberProfile as any,
      activeMemberNote: computed(() => ''),
      expandedProfileNote: computed(() => ''),
      updateProfileNote: vi.fn(),
      openSelfProfile: vi.fn(),
      openExpandedProfileFromMemberPopout: vi.fn(),
      openExpandedProfileFromSelfPopout: vi.fn(),
      openExpandedProfilePanelForUserId: vi.fn(),
      expandDmProfileToFullModal: vi.fn(),
      handleExpandedProfileOpenProfile: vi.fn(),
      handleExpandedProfileOpenDM,
      handleMemberPopoutQuickDm: vi.fn(async () => undefined),
      handleExpandedProfileRemoveFriend: vi.fn(),
      handleExpandedProfileCancelOutgoingFriendRequest: vi.fn(),
      handleProfileBlockUser: vi.fn(async () => undefined),
      handleProfileUnblockUser: vi.fn(async () => undefined),
      handleProfileReportUser: vi.fn(async () => undefined),
      isExpandedProfileTargetBlocked: computed(() => false),
      isExpandedProfileOutgoingRequest: computed(() => false),
      isMemberPopoutTargetBlocked: computed(() => false),
      isExpandedProfileFriend: computed(() => false),
      isMemberPopoutFriend: computed(() => false),
      isMemberPopoutCanSendFriendRequest: computed(() => false),
      memberListUsers: computed(() => []),
      serverSettingsMemberUsers: computed(() => []),
      usersForChannelPanel: computed(() => []),
      usersForMentionAutocomplete: computed(() => []),
      onExpandedProfileModalUpdate: vi.fn(),
      expandedProfile: ref<{ id?: string } | null>({ id: 'u1' }),
      selectDmUser: vi.fn(async () => null),
      selectDMTab: vi.fn(),
      sendFriendRequest,
      memberPopoutOpenRolesPanel: ref(false),
      isSystemSettingsOpen: ref(false),
      isUserSettingsOpen: ref(false),
      memberListCollapsed: ref(false),
      memberListWidth: ref(240),
      activeMemberProfile: activeMemberProfile as any,
      membersForMemberList: computed(() => []),
      toggleMemberList: vi.fn(),
    } as Parameters<typeof useAppLayoutContextProfileSlice>[0]);

    slice.openExpandedProfileDmFromComposable('u2', vi.fn(), vi.fn());
    expect(handleExpandedProfileOpenDM).toHaveBeenCalled();
    slice.handleExpandedProfileSendFriendRequest('u3');
    expect(sendFriendRequest).toHaveBeenCalledWith('u3');
    slice.handleCallViewOpenProfile('u4', null);
    expect(openMemberProfile).toHaveBeenCalledWith('u4', null);

    expect(slice.memberProfileUserId.value).toBe(null);
    activeMemberProfile.value = { id: 'pop-user' } as any;
    expect(slice.memberProfileUserId.value).toBe('pop-user');
  });

  it('voice/messaging/server slices pass through provided values', () => {
    const voice = useAppLayoutContextVoiceSlice({
      getVcActivityPresenceForUser: () => [],
      getVcChannelActivityPresenceForChannel: () => [],
      effectiveVcActivityKingUserId: computed(() => ''),
      activeVoiceChannelParticipants: ref([]),
      liveKitState: computed(() => 'idle'),
      liveKitNetworkStats: computed(() => null),
      liveKitRoom: null,
      vcRemoteParticipants: ref([]),
      vcMirrorCamera: ref(false),
      switchVcCamera: vi.fn(),
      setVcVideoQuality: vi.fn(),
      speakingMap: computed(() => ({})),
      localSpeaking: computed(() => false),
      localAudioLevel: computed(() => 0),
      switchMicDevice: vi.fn(),
      switchSpeakerDevice: vi.fn(),
      setLkOutputVolume: vi.fn(),
      reapplyVoiceProcessing: vi.fn(async () => undefined),
      setMicTestListenDeafen: vi.fn(),
      currentVoiceChannelId: ref(''),
      currentVoiceChannelName: ref(''),
      dmCallDeafened: ref(false),
      dmCallFullscreen: ref(false),
      dmCallMuted: ref(false),
      dmCallQuarterView: ref(false),
      dmCallMatchesActiveChannel: ref(true),
      dmCallVideo: ref(false),
      dmCallScreenshare: ref(false),
      dmCallCallViewParticipants: computed(() => []),
      dmCallWithUserId: ref<string | null>(null),
      dmCallRinging: ref(false),
      dmCallAwaitingAccept: ref(false),
      dmCallIncoming: ref<any>(null),
      dmCallRingRemoteVanishing: ref(false),
      dmCallGlassPeer: computed(() => null),
      dmCallVoiceStripThreadId: computed(() => null),
      dmCallVoiceStripTitle: computed(() => ''),
      channelPanelVoiceChannelId: computed(() => ''),
      channelPanelVoiceChannelName: computed(() => ''),
      channelPanelVcMutedEffective: computed(() => false),
      channelPanelVcDeafenedEffective: computed(() => false),
      channelPanelVcVideoEffective: computed(() => false),
      channelPanelVcScreenshareEffective: computed(() => false),
      onChannelPanelVcMuted: vi.fn(),
      onChannelPanelVcDeafened: vi.fn(),
      onChannelPanelVcVideo: vi.fn(),
      onChannelPanelVcScreenshare: vi.fn(),
      onGuildChannelVcMuted: vi.fn(),
      onGuildChannelVcDeafened: vi.fn(),
      onGuildChannelVcVideo: vi.fn(),
      onGuildChannelVcScreenshare: vi.fn(),
      onDmCallVcMuted: vi.fn(),
      onDmCallVcDeafened: vi.fn(),
      onDmCallVcVideo: vi.fn(),
      onDmCallVcScreenshare: vi.fn(),
      applyDmCallDeafened: vi.fn(),
      toggleDmCallMuted: vi.fn(),
      handleJoinVoice: vi.fn(),
      handleJoinVoiceIfAllowed: vi.fn(),
      handleLeaveVoice: vi.fn(),
      handleChannelVoicePanelLeave: vi.fn(),
      onJoinVoice: vi.fn(),
      onJoinVoiceUi: vi.fn(),
      onLeaveVoice: vi.fn(),
      onLeaveVoiceUi: vi.fn(),
      onVcChatButtonClick: vi.fn(),
      isViewingVoiceChannel: computed(() => false),
      updateVcVideoIfAllowed: vi.fn(),
      isScreenSharePickerOpen: ref(false),
      isDesktopStreamingControlOpen: ref(false),
      desktopStreamingControlMode: ref<'screen' | 'camera'>('screen'),
      desktopStreamingPreferences: ref({
        screenQuality: '720p30',
        screenContentHint: 'detail',
        screenIncludeAudio: true,
        cameraQuality: '720p',
      }),
      fullscreenStreamParticipantId: ref<string | null>(null),
      vcActivityUi: ref({
        phase: 'closed' as const,
        youtubeVideoId: null,
        youtubeBrowseOpen: true,
        playlist: [],
        currentIndex: 0,
      }),
      openVcActivityPicker: vi.fn(),
      openVcActivityYoutubeBrowse: vi.fn(),
      openVcActivityWordle: vi.fn(),
      openVcActivityHangman: vi.fn(),
      openVcActivityTicTacToe: vi.fn(),
      vcHangmanActivity: computed(() => null),
      hangmanRosterUserIds: computed(() => []),
      commitVcHangmanWord: () => null,
      requestVcHangmanGuessLetter: vi.fn(),
      requestVcHangmanNextRound: vi.fn(),
      vcCodenamesActivity: computed(() => null),
      codenamesRosterUserIds: computed(() => []),
      vcCodenamesSpymasterKey: computed(() => null),
      commitVcCodenamesDeal: vi.fn(() => null),
      requestVcCodenamesSetup: vi.fn(),
      requestVcCodenamesClue: vi.fn(),
      requestVcCodenamesReveal: vi.fn(),
      requestVcCodenamesEndTurn: vi.fn(),
      requestVcCodenamesNewGame: vi.fn(),
      requestVcCodenamesPushKeyToOrchestrator: vi.fn(),
      openVcActivityOpenGuessr: vi.fn(),
      openVcActivitySkribblIo: vi.fn(),
      openVcActivityGarticPhone: vi.fn(),
      openVcActivityKrunker: vi.fn(),
      openVcActivityCodenames: vi.fn(),
      openVcActivityRichup: vi.fn(),
      openVcActivityGooberDash: vi.fn(),
      openVcActivitySmashKarts: vi.fn(),
      openVcActivityBasketballStars2026: vi.fn(),
      openVcActivityClusterRush: vi.fn(),
      setVcActivityYoutubeVideo: vi.fn(),
      setVcYoutubeBrowseOpen: vi.fn(),
      addVcYoutubeToQueue: vi.fn(),
      removeVcYoutubeFromQueue: vi.fn(),
      moveVcYoutubeInQueue: vi.fn(),
      playVcYoutubeAtIndex: vi.fn(),
      playVcYoutubeNext: vi.fn(),
      playVcYoutubePrevious: vi.fn(),
      closeVcActivity: vi.fn(),
      vcYoutubeRemotePlayback: shallowRef(null),
      publishVcYoutubePlaybackSync: vi.fn(),
      vcYoutubePlaybackShouldPublish: computed(() => true),
      handleScreenSharePickerConfirm: vi.fn(async () => undefined),
      openDesktopStreamingControl: vi.fn(),
      closeDesktopStreamingControl: vi.fn(),
      handleDesktopStreamingControlConfirm: vi.fn(async () => undefined),
      handleToggleScreenshare: vi.fn(),
      handleStopScreenShare: vi.fn(),
      getLocalScreenTrack: vi.fn(),
      getLocalCameraTrack: vi.fn(),
      getRemoteParticipantVolume: vi.fn(() => 100),
      setRemoteParticipantVolume: vi.fn(),
      vcDeafened: ref(false),
      applyVcDeafened: vi.fn(),
      vcMuted: ref(false),
      vcScreenshare: ref(false),
      vcVideo: ref(false),
      isVcActive: computed(() => false),
      isVcConnected: computed(() => false),
      isVcConnecting: computed(() => false),
      isVcDisconnecting: computed(() => false),
      joinVoiceChannel: vi.fn(),
      leaveVoiceChannel: vi.fn(),
    } as any);
    const messaging = useAppLayoutContextMessagingSlice({
      handleGoToChannel: vi.fn(),
      handleGoToMessage: vi.fn(),
      handlePollVote: vi.fn(),
      handleReact: vi.fn(),
      pinMessage: vi.fn(),
      toggleReaction: vi.fn(),
      votePoll: vi.fn(),
      recordReaction: vi.fn(),
      removeReactionFavorite: vi.fn(),
      topReactions: computed(() => []),
      goToPinnedMessage: vi.fn(),
      goToSearchPage: vi.fn(),
      searchError: ref(''),
      searchLoading: ref(false),
      searchResultMessages: computed(() => []),
      searchResultPage: ref(1),
      searchScopeHint: computed(() => ''),
      searchText: ref(''),
      paginatedSearchResults: computed(() => []),
      totalPages: computed(() => 1),
      onSearchInput: vi.fn(),
      clearSearch: vi.fn(),
      forwardModalOpen: ref(false),
      forwardPickerDestinations: computed(() => []),
      forwardModalSourceSummary: computed(() => null),
      openForwardMessagePicker: vi.fn(),
      closeForwardMessagePicker: vi.fn(),
      submitForwardedMessage: vi.fn(),
      socketSendMessage: vi.fn(),
      sendMessage: vi.fn(),
      searchActiveTab: ref('all'),
      searchFilter: ref({}),
      searchIsLoading: ref(false),
      searchResults: ref([]),
      searchStatus: ref('idle'),
    } as any);
    const rail = useAppLayoutContextServerRailSlice({
      handleServerRailInvite: vi.fn(),
      handleServerRailMarkRead: vi.fn(),
      handleChannelMarkRead: vi.fn(),
      handleServerRailLeave: vi.fn(),
      handleServerRailNotificationSettings: vi.fn(),
      handleServerRailSettings: vi.fn(),
      openServerFromMore: vi.fn(),
      openServerSettingsFromUrl: vi.fn(),
      openServerSettings: vi.fn(),
      openServerSettingsIfAllowed: vi.fn(),
      openInviteModal: vi.fn(),
      onServerSettingsModalUpdate: vi.fn(),
      onServerSettingsModalActiveSectionUpdate: vi.fn(),
      onLeaveServerModalUpdate: vi.fn(),
      confirmLeaveServerFromModal: vi.fn(),
      isLeaveServerModalOpen: ref(false),
      leaveServerModalServerName: ref(''),
      leaveServerModalVariant: ref('confirm'),
      openServerNotificationSettings: vi.fn(),
      handleServerNotificationSave: vi.fn(),
      serverNotificationLevelsMap: computed(() => ({})),
      serverPingKindByServerId: computed(() => ({})),
      serverPingBubbleByServerId: computed(() => ({})),
      serverPingChannelDotsByServerId: computed(() => ({})),
      serverUnreadActivityDotByServerId: computed(() => ({})),
      channelMissedActivityByChannelId: computed(() => ({})),
      currentServerNotificationLevel: computed(() => null),
      isServerNotificationSettingsOpen: ref(false),
      canDeleteCurrentServer: computed(() => false),
      canOpenServerSettings: computed(() => false),
      canOpenServerSettingsForServer: vi.fn(() => false),
      canOpenInviteForServer: vi.fn(() => false),
      reorderVisibleServers: vi.fn(),
      syncVanityAcrossServerLists: vi.fn(),
      selectedServerId: computed(() => 's1'),
      servers: computed(() => [{ id: 's1' }]),
      isServerUnread: () => false,
      onOpenCreateChannel: vi.fn(),
      hasGuildChannelChrome: computed(() => true),
    } as any);

    const shellLayout = useAppLayoutContextShellLayoutSlice({
      toggleChannelPanel: vi.fn(),
      openDMPanel: vi.fn(),
    });

    expect(typeof voice.handleJoinVoice).toBe('function');
    expect(typeof messaging.handleGoToMessage).toBe('function');
    expect(typeof rail.handleServerRailInvite).toBe('function');
    expect(typeof rail.handleServerRailMarkRead).toBe('function');
    expect(typeof shellLayout.toggleChannelPanel).toBe('function');
  });

  it('dm / moderation / shell chrome slices pass through', () => {
    const dm = useAppLayoutContextDmSlice({
      echoDmPeerByChannelId: ref(new Map()),
      echoDmThreadIds: ref(new Set()),
      echoBlockedUserIds: ref(new Set()),
      dmIncomingRailCluster: computed(() => ({
        avatars: [],
        overflowCount: 0,
        totalUnreadCount: 0,
      })),
      selectMessageRequest: vi.fn(),
      ignoreMessageRequest: vi.fn(),
      returnFromMessageRequests: vi.fn(),
      acceptFriendRequest: vi.fn(),
      declineFriendRequest: vi.fn(),
      cancelFriendRequest: vi.fn(),
      sendFriendRequest: vi.fn(),
      handleDmMarkRead: vi.fn(),
      handleAcceptMessageRequest: vi.fn(),
      dmGroupFriends: computed(() => []),
      dmInboxEntriesForPanel: computed(() => []),
      dmUsersForDmPanel: computed(() => []),
      groupDMListForPanel: computed(() => []),
      isEchoUserFriend: () => false,
      isEchoUserIncomingFriendRequest: () => false,
      isEchoUserOutgoingFriendRequest: () => false,
      selectIncomingDmFromRail: vi.fn(),
      selectIncomingGroupDmFromRail: vi.fn(),
      openDmInboxFromRailOverflow: vi.fn(),
      groupDMs: ref({}),
      groupDMPreselectedIds: ref([]),
      groupDMLockedIds: ref([]),
      groupDmMaxMembers: computed(() => 10),
      dmActiveTab: ref('inbox'),
      dmPanelWidth: ref(240),
      startDmPanelResize: vi.fn(),
      dmPartnerUser: computed(() => null),
      guestFriendsLocked: computed(() => false),
      handleCreateGroupDM: vi.fn(),
      handleKickGroupDmMember: vi.fn(),
      handleLeaveGroupDm: vi.fn(),
      onRemoveGroupDmMember: vi.fn(),
      onLeaveGroupDm: vi.fn(),
      onOpenAddMembersToGroupDm: vi.fn(),
      handleSelectGroupDM: vi.fn(),
      handleUpdateGroupFromSettings: vi.fn(),
      openGroupDMModal: vi.fn(),
      openGroupOverviewPanel: vi.fn(),
      openGroupSettingsFromHeader: vi.fn(),
      isGroupDM: computed(() => false),
      isGroupDMModalOpen: ref(false),
      isGroupDMSettingsOpen: ref(false),
      groupDmSettingsInitialFocus: ref(null),
      activeGroupSettingsId: ref(null),
      isGroupOverviewOpen: ref(false),
    } as any);

    const mod = useAppLayoutContextModerationSlice({
      canModerateMemberInServer: () => false,
      canVcModerateMember: () => false,
      canModerateMemberActionInServer: () => false,
      canChangeMemberNicknameInServer: () => false,
      canModerateMessageAuthor: () => false,
      moderationModalOpen: ref(false),
      moderationAction: ref(null),
      moderationTargetUserId: ref(null),
      moderationTargetUser: computed(() => null),
      handleModerateUser: vi.fn(),
      onModerationModalConfirm: vi.fn(),
      handleVcModerate: vi.fn(),
    } as any);

    const chrome = useAppLayoutContextShellChromeSlice({
      ExploreView: null,
      MORE_SERVERS_PANEL_WIDTH: 300,
      MORE_SERVERS_COMPACT_WIDTH: 72,
      DM_PANEL_WIDTH: 240,
      appGridTemplateColumns: computed(() => ''),
      expandChannels: vi.fn(),
      exploreDiscoverableServers: ref([]),
      isExploreView: computed(() => false),
      welcomeBackExploreGate: computed(() => false),
      welcomeBackExploreMemberEmptyDirectory: computed(() => false),
      showWelcomeBackSlimBanner: computed(() => false),
      showNsfwChatGate: computed(() => false),
      acknowledgeNsfwChannel: vi.fn(),
      declineNsfwGate: vi.fn(),
      mainContentColumns: computed(() => ''),
      mainContentColumnsEffective: computed(() => ''),
      addServerInitialView: ref('initial'),
      addServerJoinError: ref(''),
      addServerCreateBusy: ref(false),
      joinEchoServerWithInviteRaw: vi.fn(),
      handleJoinWithInviteLink: vi.fn(),
      handleCreateServer: vi.fn(),
      handleJoinDiscoverableServer: vi.fn(),
      isServerEmptyOnboarding: computed(() => false),
      isJoinServerConfirmModalOpen: ref(false),
      joinServerConfirmPreview: ref(null),
      joinServerConfirmBusy: ref(false),
      confirmJoinServerFromModal: vi.fn(),
      onJoinServerConfirmModalUpdate: vi.fn(),
      isServerApplicationModalOpen: ref(false),
      serverApplicationPayload: ref(null),
      serverApplicationBusy: ref(false),
      onServerApplicationModalUpdate: vi.fn(),
      confirmServerApplicationSubmittedFromModal: vi.fn(),
    } as any);

    expect(typeof dm.handleAcceptMessageRequest).toBe('function');
    expect(typeof mod.handleModerateUser).toBe('function');
    expect(typeof chrome.expandChannels).toBe('function');
  });
});
