import {
  computed,
  defineAsyncComponent,
  ref,
  shallowRef,
  watch,
  type Ref,
} from 'vue';
import { usePollVotes } from '@/composables/usePollVotes';
import { useReactionFavorites } from '@/composables/useReactionFavorites';
// Sub-composables
// `voiceMlsSession` pulls in the ts-mls crypto stack; it is dynamically imported
// at the voice-event handler below so it stays off the first-paint AppLayout chunk.
import { useAppLayoutSearchIntegration } from './useAppLayoutSearchIntegration';
import { useAppLayoutProfilesDomain } from './useAppLayoutProfilesDomain';
import { useAppLayoutDiscordBotPoll } from './useAppLayoutDiscordBotPoll';
import { useAppLayoutForwardMessage } from './useAppLayoutForwardMessage';
import { useAppLayoutGroupDmManagement } from './useAppLayoutGroupDmManagement';
import { useAppLayoutMentionAutocompleteUsers } from './useAppLayoutMentionAutocompleteUsers';
import { useAppLayoutMentionAutocompleteRoles } from './useAppLayoutMentionAutocompleteRoles';
import { useAppLayoutMessageActions } from './useAppLayoutMessageActions';
import { useAppLayoutMentionNotifications } from './useAppLayoutMentionNotifications';
import { useAddServerFlow } from './useAddServerFlow';
import { useAppLayoutGuestQuickDm } from './useAppLayoutGuestQuickDm';
import { useJoinServerConfirmModal } from './useJoinServerConfirmModal';
import { useServerApplicationModal } from './useServerApplicationModal';

import { buildAppLayoutExpose } from './useAppLayoutController.expose';
import { assembleAppLayoutControllerContext } from './assembleAppLayoutControllerContext';
import { buildAppLayoutAssemblyDeps } from './buildAppLayoutAssemblyDeps';
import { useComputedRefAlias } from './useComputedRefAlias';
import { useComputedOptionalRefAlias } from './useComputedOptionalRefAlias';
import { useAppLayoutMemberSurfaceSwitchLoading } from './useAppLayoutMemberSurfaceSwitchLoading';
import { useAppLayoutDmInboxPanel } from './useAppLayoutDmInboxPanel';
import { useAppLayoutDmProfileBridge } from './useAppLayoutDmProfileBridge';
import { useAppLayoutWorkspaceReadyComputed } from './useAppLayoutWorkspaceReadyComputed';
import { useDmSurfaceAdapter } from './useDmSurfaceAdapter';
import { useProfileSurfaceAdapter } from './useProfileSurfaceAdapter';
import { useChatHeaderAdapter } from './useChatHeaderAdapter';
import { createEchoServerMemberOrchestration } from '@/services/orchestration/echoServerMemberOrchestration';
import { createPromptSignInHandler } from './createPromptSignInHandler';
import { createResolveEchoDmPeerFromMap } from './createResolveEchoDmPeerFromMap';
import { createOpenMemberProfileWithRolesPref } from './createOpenMemberProfileWithRolesPref';
import { useAppLayoutMemberPopoutChromeCallbacks } from './useAppLayoutMemberPopoutChromeCallbacks';
import { useAppLayoutUserSettingsModalCallbacks } from './useAppLayoutUserSettingsModalCallbacks';
import { resolveEchoServerIdContainingChannel } from '@/features/voice/resolveEchoServerIdForGuildChannel';
import { createToggleBooleanRef } from './createToggleBooleanRef';
import { createHandleExpandedProfileOpenServer } from './createHandleExpandedProfileOpenServer';
import { createIsServerUnread } from './createIsServerUnread';
import { createOpenCreateChannelOnServer } from './createOpenCreateChannelOnServer';
import { createCanModerateMessageAuthorAdapter } from './createCanModerateMessageAuthorAdapter';
import { echoSyncCapabilities } from '@/platform/syncCapabilities';
import { createEnsurePersistedDirectDmChannelIdForInvite } from './useAppLayoutDmInvitePersistence';
import {
  createAppLayoutToggleMemberList,
  useAppLayoutCompactShellExpand,
} from './useAppLayoutCompactShellExpand';
import { useAppLayoutNotificationPrefsSync } from './useAppLayoutNotificationPrefsSync';

import type { WireAppLayoutVoiceAndRealtimeResult } from './wireAppLayoutVoiceAndRealtime';
import { useAppLayoutPresenceStatusBridge } from './useAppLayoutPresenceStatusBridge';

const ExploreView = defineAsyncComponent(
  () => import('@/features/layout/components/ExploreView.vue'),
);

export function wireAppLayoutMessagingAndProfiles(
  phase2: WireAppLayoutVoiceAndRealtimeResult,
) {
  const {
    _channelPanelVoiceTransportUsesDmCall,
    _dmCallInviteSentChannelId,
    _dmCallMutedBeforeDeafen,
    _dmCallSignal,
    _dmLiveKitJoinChannelId,
    _dmVoiceJoinTargetId,
    _isDmVoiceCallUi,
    _isOpeningDmThread,
    _joinVoiceSession,
    _liveKitVoiceApi,
    _setLkInputVolume,
    _syncLiveKitAudioFromUiStores,
    acceptFriendRequest,
    acceptMessageRequest,
    acknowledgeNsfwChannel,
    actionRailTopLayout,
    actionRegistryRef,
    activeChannelContext,
    activeChannelId,
    activeChannelMessages,
    activeChannelMessagesMap,
    activeDmThreadCallUi,
    activeGroupCallMembersVisible,
    activeGroupDM,
    activeGroupId,
    activeGroupSettingsId,
    activeMemberProfile,
    activeRailTab,
    activeVoiceChannelParticipants,
    addServerInitialView,
    addVcYoutubeToQueue,
    advanceSkrigglesRound,
    answerDmCall,
    appGridTemplateColumns,
    applyDmCallDeafened,
    applyEchoPresenceFromSocket,
    applyRealtimeAuthorHint,
    applyVcDeafened,
    applyVcYoutubeWatchTogetherRemote,
    applyVcYoutubeWatchTogetherRemoteOnVoice,
    assignHydrateEchoFromApi,
    authModalInitialLoginEntry,
    authModalInitialSubView,
    authModalInitialTab,
    authModalPasskeyOnOpen,
    authSession,
    authStateGeneration,
    beginVcActivitySessionChannelLayout,
    bumpVoiceMobileChatFromCallScrollDown,
    bumpVoiceMobileChatFromCallScrollUp,
    callOverlay,
    callVoice,
    canChangeMemberNicknameInServer,
    canCreateChannels,
    canDeleteCurrentServerComputed,
    canInviteToCurrentServer,
    canJoinPreviewVoiceChannel,
    canManageThisChannel,
    canModerateMemberActionInServer,
    canModerateMemberInServer,
    canModerateMessageAuthor,
    canOpenInviteForServer,
    canVcModerateMember,
    cancelFriendRequest,
    categoriesForServer,
    categorySettingsEchoPermissionEditor,
    categorySettingsTarget,
    channelAttentionByChannelId,
    channelDisplayNameByChannelId,
    channelIconResolver,
    channelMissedActivityByChannelId,
    channelModals,
    channelPanelBubbleMode,
    channelPanelCollapsed,
    channelPanelVcDeafenedEffective,
    channelPanelVcMutedEffective,
    channelPanelVcScreenshareEffective,
    channelPanelVcVideoEffective,
    channelPanelVoiceChannelId,
    channelPanelVoiceChannelName,
    channelPanelWidth,
    channelSettingsCategoryAutoDeleteAfterSeconds,
    channelSettingsCategoryPermissionDefaults,
    channelSettingsEchoPermissionEditor,
    channelSettingsTarget,
    channelTree,
    chatMessageNavBridge,
    closeDMPanel,
    closeGuildMobileVcLobby,
    closePinsDropdown,
    closeVcActivity,
    codenamesRosterUserIds,
    collapseMembers,
    commitSkrigglesWordChoice,
    commitVcCodenamesDeal,
    commitVcHangmanWord,
    compactGuildTriPaneChannelPanelOpen,
    compactPagerPane,
    confirmLeaveServerFromModal,
    continueAsGuest,
    createChannelCategoryNames,
    createChannelCategoryOptions,
    createChannelInitialCategoryId,
    createDirectHexInvite,
    currentServerNotificationLevel,
    currentUser,
    currentUserComputed,
    currentUserIdForSocket,
    currentVoiceChannelId,
    currentVoiceChannelName,
    customStatus,
    declineDmCall,
    declineFriendRequest,
    declineNsfwGate,
    deleteCategoryById,
    deleteChannelById,
    desktopStreamingControlMode,
    desktopStreamingPreferences,
    devModeIdsEnabled,
    devSettings,
    directHexInviteBusy,
    directHexInviteLink,
    discordOnlineByUserId,
    dismissVcTicTacToeInvite,
    dispatchNav,
    dmActiveTab,
    dmAttentionByChannelId,
    dmCallAwaitingAccept,
    dmCallCallViewParticipants,
    dmCallDeafened,
    dmCallFullscreen,
    dmCallGlassPeer,
    dmCallIncoming,
    dmCallLobbyAfterSelfLeave,
    dmCallMatchesActiveChannel,
    dmCallMuted,
    dmCallQuarterView,
    dmCallRingRemoteVanishing,
    dmCallRingUi,
    dmCallRinging,
    dmCallScreenshare,
    dmCallVideo,
    dmCallVoiceStripThreadId,
    dmCallVoiceStripTitle,
    dmCallWithUserId,
    dmCallWithUserIdForShellLog,
    dmIncomingRailCluster,
    dmPanelWidth,
    dmPartnerUser,
    dmPartnerUserIdForGroupDm,
    dmRailUnread,
    dmSocial,
    dmUnreadByChannelIdForPanel,
    echoAttention,
    echoBlockedUserIds,
    echoCanContext,
    echoCapabilitiesForServerId,
    echoChannelHistory,
    echoDmActiveCallParticipantUserIdsByChannelId,
    echoDmLastActivityAtMsByChannelId,
    echoDmLastActivityIdByChannelId,
    echoDmPeerByChannelId,
    echoDmState,
    echoDmThreadIds,
    echoLifecycle,
    echoSession,
    echoWorkspaceError,
    effectiveActiveChannel,
    effectiveVcActivityKingUserId,
    endDmCall,
    endVcActivitySessionChannelLayout,
    ensureReplyTargetMessage,
    expandChannels,
    expandChannelsGrid,
    expandMembers,
    expandVoiceSideChat,
    expandedProfile,
    expandedProfileTargetUserId,
    exploreDiscoverableServers,
    explorePublicDirectoryEmpty,
    favoriteDmInboxStore,
    findChannelContextById,
    friendshipQueries,
    fullscreenStreamParticipantId,
    getChatSoundMemberRoleIds,
    getFirstTextChannelId,
    getLatestDmInboxTargetForRailRef,
    getLatestDmPeerUserIdForRail,
    getPinnedIdsSnapshot,
    getRemoteParticipantVolume,
    getServerChannelInfoForMainSurface,
    getVcActivityPresenceForUser,
    getVcChannelActivityPresenceForChannel,
    getVcLocalCameraTrack,
    getVcLocalScreenTrack,
    goToPinnedMessage,
    gridChrome,
    gridMoreServersCompactWidth,
    gridMoreServersPanelWidth,
    groupDMLockedIds,
    groupDMPreselectedIds,
    groupDMs,
    groupDmMaxMembers,
    groupDmSettingsInitialFocus,
    guestCaptchaSiteKey,
    guestFriendsLocked,
    guestSession,
    guildMobileVcLobby,
    guildMod,
    handleAcceptMessageRequest,
    handleActiveChannelChangeNavigation,
    handleCategoryDelete,
    handleCategoryReorder,
    handleCategorySettingsSave,
    handleChannelDelete,
    handleChannelMarkRead,
    handleChannelReorder,
    handleChannelSettingsSave,
    handleChannelVoicePanelLeave,
    handleCreateCategorySubmit,
    handleCreateChannelModalSubmit,
    handleCreateChannelSubmit,
    handleDmMarkRead,
    handleDmRailMarkAllRead,
    handleEchoDmActivity,
    handleEchoDmCall,
    handleEchoDmThreadActivity,
    handleGoToChannel,
    handleGoToMessageDelegated,
    handleJoinVoiceNavigation,
    handleLeaveVoiceNavigation,
    handleModerateUser,
    handleServerDeleted,
    handleServerNotificationSave,
    handleServerRailInvite,
    handleServerRailLeave,
    handleServerRailMarkAllRead,
    handleServerRailMarkRead,
    handleServerRailNotificationSettings,
    handleServerRailSettings,
    handleVcModerate,
    hangmanRosterUserIds,
    hasGuildChannelChrome,
    hiddenDmInboxStore,
    hostCallbacks,
    hydrateAfterGuestAccountUpgrade,
    hydrateEchoFromApi,
    ignoreMessageRequest,
    immediateShellSwitchPending,
    inviteApplicationsEnabled,
    inviteCanCreateDirectHexInvite,
    inviteJoinLinksEnabled,
    inviteLanding,
    inviteLandingActiveComputed,
    inviteLandingActiveRef,
    inviteLinkForServer,
    inviteLinkFromApi,
    inviteLinkFromSelectedServer,
    inviteLinkLookupPending,
    inviteModalVoiceChannelId,
    inviteModalVoiceChannelName,
    isAddServerModalOpen,
    isAuthModalOpen,
    isAuthenticatedComputed,
    isChannelActive,
    isChannelPanelSwitchLoading,
    isCompactGuildSplitShell,
    isCompactShell,
    isCreateCategoryModalOpen,
    isCreateChannelModalOpen,
    isDMPanelOpen,
    isDesktopStreamingControlOpen,
    isDmUiContext,
    isEchoRoleBootstrapLoading,
    isEchoUserBlocked,
    isExpandedProfileModalOpen,
    isExpandedProfileSidePanel,
    isExploreView,
    isGroupDMComputed,
    isGroupDMModalOpen,
    isGroupDMSettingsOpen,
    isGroupOverviewOpen,
    isGuestCaptchaModalOpen,
    isGuestComputed,
    isGuestDisplayNameModalOpen,
    isGuestUpgradeModalOpen,
    isGuestWelcomePrefsModalOpen,
    isGuildShellSettledForSwitchPending,
    isGuildShellSettling,
    isInDMModeComputed,
    isInDmThreadOrIdleMainSurface,
    isInviteModalOpen,
    isKnownDmChannelId,
    isLeaveServerModalOpenRef,
    isLiveReactionReady,
    isLiveSocketReady,
    isMemberPopoutOpen,
    isMessageSurfaceSwitchLoading,
    isMoreServersCompact,
    isMoreServersPanelOpen,
    isMoreServersPinned,
    isPersistedEchoDmThread,
    isPinsDropdownOpen,
    isReactionPersistReady,
    isScreenSharePickerOpen,
    isSelfProfilePopoutOpen,
    isServerEmptyOnboarding,
    isServerNotificationSettingsOpen,
    isServerRailFastSwitchPending,
    isServerSettingsModalOpen,
    isSettingsModalOpen,
    isSystemSettingsOpen,
    isVcActive,
    isVcConnected,
    isVcConnecting,
    isVcDisconnecting,
    isViewingVoiceChannel,
    joinVoiceChannel,
    lastOnlineAtByUserId,
    layoutDims,
    leaveDmCallVoice,
    leaveDmUiIfViewingUser,
    leaveServerModalServerNameRef,
    leaveServerModalVariantRef,
    leaveVoiceChannel,
    leaveVoiceSession,
    linkedDiscordState,
    linkedDiscordUserId,
    liveCaps,
    liveChannelCapabilities,
    liveChannelCapabilitiesRefreshKey,
    liveKitNetworkStats,
    liveKitRoom,
    liveKitState,
    localAudioLevel,
    localSpeaking,
    mainContentColumns,
    mainContentColumnsEffective,
    mainSurface,
    markActiveChannelAsRead,
    markEchoChannelAsRead,
    markMemberPanelCollapsedByUser,
    markMemberPanelExpandedByUser,
    markServerAsReadForRail,
    memberListShowGuests,
    memberPanelAutoCollapseUserOverride,
    memberPanelCollapsed,
    memberPanelCollapsedEffective,
    memberPanelWidth,
    memberPopoutAnchor,
    memberPopoutOpenRolesPanel,
    mergeEchoBlockedFromApi,
    mergeEchoDmThread,
    mergeEchoDmThreadFromRealtime,
    mergeEchoDmThreadsFromApi,
    micTestListenDeafenActive,
    mockDataModeOffComputed,
    moderationAction,
    moderationModalOpen,
    moderationTargetUser,
    moderationTargetUserId,
    moveVcYoutubeInQueue,
    narrowChannelPanelForActivityOverflowStep,
    navTraceId,
    navigateToDmForAnswerRef,
    newlyCreatedServerId,
    nsfwGate,
    onCategorySettingsModalOpenUpdate,
    onChannelPanelVcDeafened,
    onChannelPanelVcMuted,
    onChannelPanelVcScreenshare,
    onChannelPanelVcVideo,
    onChannelSettingsModalOpenUpdate,
    onDesktopCameraStarted,
    onDmCallVcDeafened,
    onDmCallVcMuted,
    onDmCallVcScreenshare,
    onDmCallVcVideo,
    onEchoMessageFailedGuest,
    onGuestCaptchaVerified,
    onGuildChannelVcDeafened,
    onGuildChannelVcMuted,
    onGuildChannelVcScreenshare,
    onGuildChannelVcVideo,
    onJoinVoice,
    onLeaveServerModalUpdate,
    onLeaveVoice,
    onModerationModalConfirm,
    onSelectDmUser,
    onVcChatButtonClickNavigation,
    openAuthModal,
    openCategorySettings,
    openChannelSettings,
    openCreateCategoryModal,
    openCreateChannelModal,
    openDmInboxFromRailOverflow,
    openGroupDmOnServerImpl,
    openGuestUpgradeForDmRef,
    openGuestUpgradeModal,
    openGuildMobileVcLobby,
    openLeaveServerConfirmModal,
    openLeaveServerOwnerBlockedModal,
    openServerFromMore,
    openServerNotificationSettings,
    openServerSettingsFromUrl,
    openServerSurface,
    openUserSettingsToDiscordFromAddServer,
    openVcActivityClusterRush,
    openVcActivityClusterRushOnVoice,
    openVcActivityCodenames,
    openVcActivityCodenamesOnVoice,
    openVcActivityGarticPhone,
    openVcActivityGarticPhoneOnVoice,
    openVcActivityGooberDash,
    openVcActivityGooberDashOnVoice,
    openVcActivityHangman,
    openVcActivityHangmanOnVoice,
    openVcActivityKrunker,
    openVcActivityKrunkerOnVoice,
    openVcActivityOpenGuessr,
    openVcActivityOpenGuessrOnVoice,
    openVcActivityPicker,
    openVcActivityPickerOnVoice,
    openVcActivityRichup,
    openVcActivityRichupOnVoice,
    openVcActivitySkribblIo,
    openVcActivitySkribblIoOnVoice,
    openVcActivitySkriggles,
    openVcActivitySkrigglesOnVoice,
    openVcActivitySmashKarts,
    openVcActivitySmashKartsOnVoice,
    openVcActivityTicTacToe,
    openVcActivityTicTacToeOnVoice,
    openVcActivityWordle,
    openVcActivityWordleOnVoice,
    openVcActivityYoutubeBrowse,
    openVcActivityYoutubeBrowseOnVoice,
    pfpBarExpanded,
    pinChannelId,
    pinMessage,
    pinPreview,
    pinToggleHandlers,
    pinnedMessageIdsForCurrentChannel,
    pinnedMessagesForDropdown,
    pinsButtonRefDm,
    pinsButtonRefServer,
    pinsDropdownRect,
    pinsEnabled,
    pinsIntegration,
    platform,
    playVcYoutubeAtIndex,
    playVcYoutubeNext,
    playVcYoutubePrevious,
    presenceByUserId,
    presenceMobileByUserId,
    profileNotes,
    publishSkrigglesCanvasCmd,
    publishSkrigglesCanvasSnapshot,
    publishSkrigglesStrokeBatch,
    publishVcYoutubePlaybackSync,
    rawCategoriesForServer,
    readStateByChannelId,
    reapplyVoiceProcessing,
    reconnectGuildVoiceAfterE2eeRotation,
    refreshEchoSocialFromApi,
    refreshRoleData,
    rejoinDmCallVoice,
    removeVcYoutubeFromQueue,
    requestVcCodenamesClue,
    requestVcCodenamesEndTurn,
    requestVcCodenamesNewGame,
    requestVcCodenamesPushKeyToOrchestrator,
    requestVcCodenamesReveal,
    requestVcCodenamesSetup,
    requestVcHangmanGuessLetter,
    requestVcHangmanNextRound,
    requestVcTicTacToeMove,
    requestVcTicTacToeRematch,
    resetChannelWidth,
    resetDmPanelWidth,
    resetMemberWidth,
    resetVoiceSideChatWidth,
    resolveMemberHighestRole,
    resolvePreviewChannelPermission,
    respondVcTicTacToeInvite,
    returnFromMessageRequests,
    rolePreviewState,
    roleUi,
    sealWithGroupDmAndNavigation,
    selectDMTab,
    selectDmUser,
    selectExploreTab,
    selectGroupDmForIncomingRail,
    selectIncomingDmFromRail,
    selectIncomingGroupDmFromRail,
    selectMessageRequest,
    selectServerViaStore,
    selectServersRailOnly,
    selectServersTab,
    selectedDMUserId,
    selectedMessageRequestId,
    selectedServerEcho,
    selectedServerIdRef,
    selectedServerInvite,
    selectedServerRef,
    selectedServerView,
    selfProfile,
    selfProfileAnchor,
    sendFriendRequest,
    sendMessageViaSocket,
    sendVcTicTacToeChallenge,
    serverAttentionByServerId,
    serverNotificationLevelByServerId,
    serverNotificationLevelsMap,
    serverPingBubbleByServerId,
    serverPingChannelDotsByServerId,
    serverPingKindByServerId,
    serverRowsRef,
    serverSettingsModalActiveSection,
    serverSettingsModalInitialSection,
    serverStore,
    serverUnreadActivityDotByServerId,
    sessionEndedMessage,
    setChannelPinsFromEcho,
    setDesktopStreamingPreferences,
    setLkOutputVolume,
    setMicTestListenDeafen,
    setPinnedMessageIdsForChannel,
    setRemoteParticipantVolume,
    setVcActivityYoutubeVideo,
    setVcVideoQuality,
    setVcYoutubeBrowseOpen,
    settingsModalActiveSection,
    settingsModalInitialSection,
    shellNavState,
    showApiFetchErrorBanner,
    showNsfwChatGate,
    showWelcomeBackSlimBanner,
    skrigglesCanvasEvents,
    skrigglesRosterUserIds,
    speakingMap,
    startChannelResize,
    startDesktopCameraStream,
    startDesktopScreenShare,
    startDmCall,
    startDmCallWithUserId,
    startDmPanelResize,
    startGroupCall,
    startGroupCallWithId,
    startMemberResize,
    startSkrigglesGame,
    startVcScreenShare,
    startVoiceSideChatResize,
    stopVcScreenShare,
    submitDmCallAcceptViaSocket,
    submitDmCallEndViaSocket,
    submitDmCallInviteViaSocket,
    submitImageSlotFillViaSocket,
    submitMessageDeleteViaSocket,
    submitMessageEditViaSocket,
    submitPinToggle,
    submitPinViaSocket,
    submitPollVoteViaSocket,
    submitReactionToggle,
    submitReactionToggleViaSocket,
    submitSkrigglesGuess,
    submitUnpinViaSocket,
    suspiciousEmptyWorkspace,
    switchMicDevice,
    switchSpeakerDevice,
    switchVcCamera,
    syncEchoPresenceFromApi,
    syncOutboundPresence,
    syncVanityAcrossServerLists,
    themeStore,
    tickSkrigglesTimers,
    toggleChannelPanelBubbleMode,
    toggleDmCallMuted,
    toggleMoreServersPanelChrome,
    togglePinsDropdown,
    toggleReactionOnMessages,
    toggleVoiceSideChat,
    uiState,
    uiTransactions,
    unpinMessage,
    updateSkrigglesSettings,
    vcActivityUi,
    vcCodenamesActivity,
    vcCodenamesSpymasterKey,
    vcDeafened,
    vcHangmanActivity,
    vcMirrorCamera,
    vcMuted,
    vcRemoteParticipants,
    vcScreenshare,
    vcSkrigglesActivity,
    vcTicTacToeActivity,
    vcTicTacToePendingInvite,
    vcVideo,
    vcYoutubePlaybackShouldPublish,
    vcYoutubeRemotePlayback,
    voiceChannelForParticipants,
    voiceMobileSheetLevel,
    voiceSideChatCollapsed,
    voiceSideChatWidth,
    watchActiveChannelWithServerChange,
    welcomeBackExploreGate,
    welcomeBackExploreMemberEmptyDirectory,
    wireDmCallSocketSubmitters,
    wireMessageGoToMessage,
    workspace,
    workspaceMembersByServer,
  } = phase2;

  const {
    openMemberProfile,
    activeMemberNote,
    expandedProfileNote,
    expandedProfileLoading,
    updateProfileNote,
    openSelfProfile,
    openExpandedProfileFromMemberPopout,
    openExpandedProfileFromSelfPopout,
    openExpandedProfilePanelForUserId,
    openExtendedProfileModalForUserId,
    expandDmProfileToFullModal,
    handleExpandedProfileOpenProfile,
    handleExpandedProfileOpenDM,
    isExpandedProfileFriend,
    handleUpdateCustomStatus: _handleUpdateCustomStatus,
    handleProfileBlockUser,
    handleProfileUnblockUser,
    handleProfileReportUser,
    isExpandedProfileTargetBlocked: isExpandedProfileTargetBlockedComputed,
    isMemberPopoutTargetBlocked: isMemberPopoutTargetBlockedComputed,
    handleChangeMemberNicknameFromMemberList,
    isEchoUserBlocked: _isEchoUserBlockedFromSafety,
    isMemberPopoutFriend,
    isMemberPopoutCanSendFriendRequest,
    isExpandedProfileOutgoingRequest,
    handleExpandedProfileCancelOutgoingFriendRequest,
    handleExpandedProfileAcceptIncomingFriendRequest,
    handleExpandedProfileDeclineIncomingFriendRequest,
    memberListUsers,
    serverSettingsMemberUsers,
    usersForChannelPanel,
    handleExpandedProfileRemoveFriend,
    onExpandedProfileModalUpdate,
  } = useAppLayoutProfilesDomain({
    workspace: {
      ...workspace,
      refreshEchoSocialFromApi,
      acceptFriendRequest,
      declineFriendRequest,
      cancelFriendRequest,
    },
    authSession,
    serverStore,
    currentUser,
    activeChannel: effectiveActiveChannel,
    selectedServerEcho,
    selectedServerView,
    customStatus,
    echoBlockedUserIds,
    isMemberPopoutOpen,
    isSelfProfilePopoutOpen,
    isExpandedProfileModalOpen,
    isExpandedProfileSidePanel,
    isGroupOverviewOpen,
    activeMemberProfile,
    expandedProfile,
    expandedProfileTargetUserId,
    profileNotes,
    memberPopoutAnchor,
    selfProfileAnchor,
    selfProfile,
    isInDMChat: isInDmThreadOrIdleMainSurface,
    isInDMMode: isInDMModeComputed,
    leaveDmUiIfViewingUser,
    canChangeMemberNicknameInServer,
    hydrateEchoFromApi,
    refreshEchoRoleData: refreshRoleData,
    workspaceMembersByServer,
    presenceByUserId,
    presenceMobileByUserId,
  });

  useAppLayoutDmProfileBridge({
    dmPartnerUser,
    isInDmThreadOrIdleMainSurface,
    isExpandedProfileSidePanel,
    isExpandedProfileModalOpen,
    expandedProfile,
    expandedProfileTargetUserId,
    isGroupOverviewOpen,
    isGroupDM: isGroupDMComputed,
    openExpandedProfilePanelForUserId,
    activeChannelId,
    echoDmPeerByChannelId,
    selectedDMUserId,
    mainSurface,
    groupDMs,
  });

  const userSettingsModalCallbacks = useAppLayoutUserSettingsModalCallbacks({
    isSettingsModalOpen,
    settingsModalInitialSection,
    settingsModalActiveSection,
  });
  const memberPopoutChromeCallbacks = useAppLayoutMemberPopoutChromeCallbacks({
    isMemberPopoutOpen,
    memberPopoutAnchor,
    memberPopoutOpenRolesPanel,
  });
  const openMemberProfileForContext = createOpenMemberProfileWithRolesPref({
    memberPopoutOpenRolesPanel,
    openMemberProfile,
  });
  const isMemberSurfaceSwitchLoading = useAppLayoutMemberSurfaceSwitchLoading({
    isServerRailFastSwitchPending,
    isGuildShellSettling,
    memberListUsers,
  });

  const usersForMentionAutocomplete = useAppLayoutMentionAutocompleteUsers({
    activeChannelId,
    mainSurface,
    isPersistedEchoDmThread,
    isGroupDM: isGroupDMComputed,
    activeGroupDM,
    selectedDMUserId,
    dmPartnerUser,
    echoDmPeerByChannelId,
    workspace,
    authSession,
    memberListUsers,
  });

  const rolesForMentionAutocomplete = useAppLayoutMentionAutocompleteRoles({
    mainSurface,
    selectedServerId: selectedServerIdRef,
    echoRoleCatalog: roleUi.echoRoleCatalog,
    echoCapabilitiesForServerId: roleUi.echoCapabilitiesForServerId,
    lightTheme: computed(() => themeStore.canonicalTheme === 'light'),
  });

  const searchIntegration = useAppLayoutSearchIntegration({
    categoriesForServer,
    activeChannelId,
    activeChannelMessages,
    searchFilterUsers: usersForMentionAutocomplete,
    authSession,
    serverStore,
    isInDMMode: isInDMModeComputed,
    echoDmThreadIds,
    selectedServer: selectedServerEcho,
    handleGoToMessage: handleGoToMessageDelegated,
  });
  const {
    searchText,
    filterChips,
    allChannels,
    isSearchActive,
    paginatedSearchResults,
    searchResultMessages,
    searchResultPage,
    totalPages,
    goToSearchPage,
    addFilter,
    removeFilter,
    clearSearch,
    searchLoading,
    searchError,
    searchScopeHint,
    onSearchInput,
    searchActiveTab,
    searchFilter,
    searchIsLoading,
    searchResults,
    searchStatus,
  } = searchIntegration;

  const socketSendMessage = sendMessageViaSocket;
  const sendMessage = sendMessageViaSocket;

  const workspaceReady = useAppLayoutWorkspaceReadyComputed(workspace.loading);

  const isGuest = isGuestComputed;

  const {
    forwardModalOpen,
    forwardPickerDestinations,
    forwardModalSourceSummary,
    openForwardMessagePicker,
    closeForwardMessagePicker,
    submitForwardedMessage,
  } = useAppLayoutForwardMessage({
    activeChannelId,
    isLiveSocketReady,
    echoDmPeerByChannelId,
    echoDmThreadIds,
    echoDmLastActivityIdByChannelId,
    groupDMs,
    users: workspace.users,
    servers: workspace.servers,
    categoriesByServer: workspace.categoriesByServer,
    sendMessage,
  });

  const { handleMemberPopoutQuickDm, onGuestAccountUpgraded } =
    useAppLayoutGuestQuickDm({
      isGuest,
      isMemberPopoutOpen,
      isSettingsModalOpen,
      settingsModalInitialSection,
      settingsModalActiveSection,
      selectDMTab,
      selectDmUser,
      sendMessage,
      hydrateAfterGuestAccountUpgrade,
      isGuestAfterUpgrade: () => authSession.backendUser?.isGuest === true,
    });

  const handleExpandedProfileOpenServer = createHandleExpandedProfileOpenServer(
    {
      openServerSurface: (serverId) => openServerSurface(serverId),
      isExpandedProfileModalOpen,
      isExpandedProfileSidePanel,
      isGroupOverviewOpen,
      expandedProfile,
      expandedProfileTargetUserId,
    },
  );

  const ensurePersistedDirectDmChannelIdForInvite =
    createEnsurePersistedDirectDmChannelIdForInvite({
      authSession,
      echoDmPeerByChannelId,
      mergeEchoDmThreadFromRealtime,
    });

  const {
    isJoinServerConfirmModalOpen: isJoinServerConfirmModalOpenRef,
    joinServerConfirmPreview: joinServerConfirmPreviewRef,
    joinServerConfirmBusy: joinServerConfirmBusyRef,
    requestJoinServerConfirm,
    onJoinServerConfirmModalUpdate,
    confirmJoinServerFromModal,
    finishJoinServerConfirmModal,
  } = useJoinServerConfirmModal();

  const {
    isServerApplicationModalOpen: isServerApplicationModalOpenRef,
    serverApplicationPayload: serverApplicationPayloadRef,
    serverApplicationBusy: serverApplicationBusyRef,
    requestServerApplicationModal,
    onServerApplicationModalUpdate,
    confirmSubmittedFromModal: confirmServerApplicationSubmittedFromModal,
    finishServerApplicationModal,
  } = useServerApplicationModal();

  const addServerFlow = useAddServerFlow({
    serverStore,
    authSession,
    workspace,
    currentUser,
    activeChannelId,
    activeRailTab,
    dmActiveTab,
    isAddServerModalOpen,
    addServerInitialView,
    isMoreServersPanelOpen,
    isMoreServersPinned,
    newlyCreatedServerId,
    getFirstTextChannelId,
    hydrateWorkspace: hydrateEchoFromApi,
    sendMessage,
    inviteLinkForServer,
    selectedServer: selectedServerEcho,
    isExploreView,
    onPromptSignIn: createPromptSignInHandler(openAuthModal),
    isPersistedEchoDmThread,
    ensurePersistedDirectDmChannelId: ensurePersistedDirectDmChannelIdForInvite,
    requestJoinServerConfirm,
    finishJoinServerConfirmModal,
    requestServerApplicationModal,
    finishServerApplicationModal,
    echoDmPeerByChannelId,
    echoDmLastActivityAtMsByChannelId,
  });
  const {
    addServerJoinError,
    addServerCreateBusy,
    addServerJoinBusy,
    addServerJoinInvitePrefill,
    exploreDirectoryJoinBusy,
    openAddServerModal,
    joinEchoServerWithInviteRaw,
    handleJoinWithInviteLink,
    handleCreateServer,
    handleJoinDiscoverableServer,
    handleInviteFriend,
    inviteableFriends,
  } = addServerFlow;

  const { votePoll: votePollMock } = usePollVotes(workspace.messages);

  const reactionFavorites = useReactionFavorites();

  const resolveEchoDmPeerForMessageActions = createResolveEchoDmPeerFromMap(
    () => echoDmPeerByChannelId.value,
  );

  const messageActions = useAppLayoutMessageActions({
    activeChannelId,
    currentUser: currentUserComputed,
    users: workspace.users,
    messages: workspace.messages,
    votePoll: votePollMock,
    submitEchoPollVote: submitPollVoteViaSocket,
    submitEchoMessageEdit: submitMessageEditViaSocket,
    submitEchoImageSlotFill: submitImageSlotFillViaSocket,
    submitEchoMessageDelete: submitMessageDeleteViaSocket,
    uiTransactions,
    isLiveSocketReady,
    toggleReaction: toggleReactionOnMessages,
    recordReaction: reactionFavorites.recordReaction,
    clearSearch,
    onSelectServerForChannel: selectServerViaStore,
    onOpenServerChannel: (serverId, channelId) =>
      openServerSurface(serverId, channelId),
    onSelectDmUser: selectDmUser,
    onSelectGroupDmChannel: (channelId) =>
      selectGroupDmForIncomingRail.value?.(channelId),
    resolveGuildServerIdForChannel: (channelId) =>
      resolveEchoServerIdContainingChannel(
        channelId,
        workspace.categoriesByServer.value,
      ),
    resolveEchoDmPeer: resolveEchoDmPeerForMessageActions,
    prefetchEchoMessage: echoChannelHistory?.prefetchUntilMessageVisible,
    onAfterDeleteMessage: undefined,
    getActiveChatMessageNav: () => chatMessageNavBridge.getActiveApi(),
    dmActiveTab,
    activeRailTab,
  });

  wireMessageGoToMessage(messageActions.handleGoToMessage);

  const {
    dmMentionNotifications,
    mentionNotificationHydrationLoading,
    resolveDmMentionNotificationChannelLabel,
    resolveDmMentionNotificationAuthorName,
    resolveDmMentionNotificationRowPreview,
    dmNotificationReadStateByChannelId,
    mentionNotificationCategoriesByServer,
    mentionNotificationServers,
    dmNotificationsReadPreset,
    dmNotificationsSourceKey,
    onOpenMentionNotification,
    onMarkMentionNotificationRead,
  } = useAppLayoutMentionNotifications({
    findChannelContextById,
    workspace,
    echoDmPeerByChannelId,
    echoDmThreadIds,
    groupDMs,
    currentUserIdForSocket,
    authSession,
    echoAttention,
    serverStore,
    activeChannelId,
    handleGoToMessage: messageActions.handleGoToMessage,
    markEchoChannelAsRead,
  });

  useAppLayoutNotificationPrefsSync({ authSession });

  const { updateStatusCast } = useAppLayoutPresenceStatusBridge({
    authSession,
    presenceByUserId,
    presenceMobileByUserId,
    updateCurrentUserStatus: messageActions.updateCurrentUserStatus,
  });

  const {
    dmInboxEntriesForPanel,
    dmUsersForDmPanelComputed,
    groupDMListForPanelComputed,
    isDmInboxUserFavorite,
    isDmInboxGroupFavorite,
    toggleFavoriteDmInbox,
    hideDmFromInboxUser,
    hideDmFromInboxGroup,
  } = useAppLayoutDmInboxPanel({
    activeRailTab,
    isDMPanelOpen,
    currentUserIdForSocket,
    workspace,
    groupDMs,
    echoDmPeerByChannelId,
    echoDmLastActivityAtMsByChannelId,
    echoDmLastActivityIdByChannelId,
    selectedDMUserId,
    activeChannelId,
    dmUnreadByChannelIdForPanel,
    activeGroupDM,
    authSession,
    hiddenDmInboxStore,
    favoriteDmInboxStore,
    mergeEchoDmThread,
  });

  const { discordBotExportReadyBanner, dismissDiscordBotExportReadyBanner } =
    useAppLayoutDiscordBotPoll({
      isAuthenticated: () => authSession.isAuthenticated,
      isAddServerModalOpen,
    });

  const toggleMemberListBase = createToggleBooleanRef(memberPanelCollapsed);
  const toggleMemberList = createAppLayoutToggleMemberList({
    isCompactShell,
    hasGuildChannelChrome,
    isCompactGuildSplitShell,
    compactPagerPane,
    memberPanelCollapsed,
    toggleMemberListBase,
    markMemberPanelExpandedByUser,
    markMemberPanelCollapsedByUser,
  });
  const toggleChannelPanel = createToggleBooleanRef(channelPanelCollapsed);
  const isServerUnread = createIsServerUnread(
    () => serverAttentionByServerId.value,
  );
  const openCreateChannelOnServer = createOpenCreateChannelOnServer({
    openServerSurface: (serverId) => openServerSurface(serverId),
    openCreateChannelModal,
  });
  const canModerateMessageAuthorForSurface =
    createCanModerateMessageAuthorAdapter(canModerateMessageAuthor);

  const {
    groupDmActions,
    handleSelectGroupDMWithGuestGuard,
    groupSettingsMembers,
    groupSettingsId,
    onOpenAddMembersToGroupDm,
    handleKickGroupDmMember,
    handleLeaveGroupDm,
  } = useAppLayoutGroupDmManagement({
    groupDMs,
    groupDMPreselectedIds,
    groupDMLockedIds,
    isGroupDMModalOpen,
    isGroupDMSettingsOpen,
    groupDmSettingsInitialFocus,
    activeGroupSettingsId,
    activeChannelId,
    selectedDMUserId,
    dmActiveTab,
    selectedMessageRequestId,
    isDMPanelOpen,
    pfpBarExpanded,
    currentUserId: currentUserIdForSocket,
    dmPartnerUserId: dmPartnerUserIdForGroupDm as unknown as Ref<string | null>,
    activeGroupId: activeGroupId as unknown as Ref<string | null>,
    selectServer: selectServerViaStore,
    isInDMChat: isInDmThreadOrIdleMainSurface as unknown as Ref<boolean>,
    isGroupOverviewOpen,
    isExpandedProfileModalOpen,
    isExpandedProfileSidePanel,
    expandedProfile,
    expandedProfileTargetUserId,
    openGroupDmOnServer: openGroupDmOnServerImpl,
    isCompactShell,
    workspace,
    currentUser,
    authSession,
    serverStore,
    mergeEchoDmThreadsFromApi,
    openGuestUpgradeModal,
    closePinsDropdown,
    clearSearch,
  });

  selectGroupDmForIncomingRail.value = handleSelectGroupDMWithGuestGuard;

  navigateToDmForAnswerRef.value = (targetId: string) => {
    const tid = targetId.trim();
    if (!tid) return;
    if (groupDMs.value[tid]) {
      handleSelectGroupDMWithGuestGuard(tid);
      if (authSession.backendUser?.isGuest === true) return;
      selectDMTab();
      return;
    }
    void selectDmUser(tid);
    if (authSession.backendUser?.isGuest === true) return;
    // `onSelectDmUser` does not switch the server rail to DM; without this, the channel
    // tree stays visible ("No channels…") and the members/search column can leak beside DM call UI.
    queueMicrotask(() => {
      selectDMTab();
    });
  };

  const { appActionRegistry, appLayoutActions } = sealWithGroupDmAndNavigation({
    groupDm: {
      ...groupDmActions,
      handleSelectGroupDM: handleSelectGroupDMWithGuestGuard,
    },
    navigation: {
      openServerSettingsFromUrl,
      openDm: selectDmUser,
    },
  });

  const context = assembleAppLayoutControllerContext(
    buildAppLayoutAssemblyDeps({
      ...phase2,
      openMemberProfileForContext,
      activeMemberNote,
      expandedProfileNote,
      updateProfileNote,
      openSelfProfile,
      openExpandedProfileFromMemberPopout,
      openExpandedProfileFromSelfPopout,
      openExpandedProfilePanelForUserId,
      openExtendedProfileModalForUserId,
      expandDmProfileToFullModal,
      handleExpandedProfileOpenProfile,
      handleExpandedProfileOpenDM,
      isExpandedProfileFriend,
      handleProfileBlockUser,
      handleProfileUnblockUser,
      handleProfileReportUser,
      isExpandedProfileTargetBlockedComputed,
      isMemberPopoutTargetBlockedComputed,
      handleChangeMemberNicknameFromMemberList,
      isMemberPopoutFriend,
      isMemberPopoutCanSendFriendRequest,
      isExpandedProfileOutgoingRequest,
      handleExpandedProfileCancelOutgoingFriendRequest,
      handleExpandedProfileAcceptIncomingFriendRequest,
      handleExpandedProfileDeclineIncomingFriendRequest,
      memberListUsers,
      serverSettingsMemberUsers,
      usersForChannelPanel,
      handleExpandedProfileRemoveFriend,
      onExpandedProfileModalUpdate,
      usersForMentionAutocomplete,
      rolesForMentionAutocomplete,
      searchText,
      filterChips,
      allChannels,
      isSearchActive,
      paginatedSearchResults,
      searchResultMessages,
      searchResultPage,
      totalPages,
      goToSearchPage,
      addFilter,
      removeFilter,
      clearSearch,
      searchLoading,
      searchError,
      searchScopeHint,
      onSearchInput,
      searchActiveTab,
      searchFilter,
      searchIsLoading,
      searchResults,
      searchStatus,
      socketSendMessage,
      sendMessage,
      workspaceReady,
      forwardModalOpen,
      forwardPickerDestinations,
      forwardModalSourceSummary,
      openForwardMessagePicker,
      closeForwardMessagePicker,
      submitForwardedMessage,
      handleMemberPopoutQuickDm,
      handleExpandedProfileOpenServer,
      addServerJoinError,
      addServerCreateBusy,
      addServerJoinBusy,
      addServerJoinInvitePrefill,
      exploreDirectoryJoinBusy,
      openAddServerModal,
      joinEchoServerWithInviteRaw,
      handleJoinWithInviteLink,
      handleCreateServer,
      handleJoinDiscoverableServer,
      handleInviteFriend,
      inviteableFriends,
      reactionFavorites,
      messageActions,
      dmMentionNotifications,
      mentionNotificationHydrationLoading,
      resolveDmMentionNotificationChannelLabel,
      resolveDmMentionNotificationAuthorName,
      resolveDmMentionNotificationRowPreview,
      dmNotificationReadStateByChannelId,
      mentionNotificationCategoriesByServer,
      mentionNotificationServers,
      dmNotificationsReadPreset,
      dmNotificationsSourceKey,
      onOpenMentionNotification,
      onMarkMentionNotificationRead,
      updateStatusCast,
      dmInboxEntriesForPanel,
      dmUsersForDmPanelComputed,
      groupDMListForPanelComputed,
      isDmInboxUserFavorite,
      isDmInboxGroupFavorite,
      toggleFavoriteDmInbox,
      hideDmFromInboxUser,
      hideDmFromInboxGroup,
      discordBotExportReadyBanner,
      dismissDiscordBotExportReadyBanner,
      toggleMemberList,
      toggleChannelPanel,
      isServerUnread,
      openCreateChannelOnServer,
      canModerateMessageAuthorForSurface,
      groupDmActions,
      handleSelectGroupDMWithGuestGuard,
      groupSettingsMembers,
      groupSettingsId,
      onOpenAddMembersToGroupDm,
      handleKickGroupDmMember,
      handleLeaveGroupDm,
      appActionRegistry,
      appLayoutActions,
      ExploreView,
      isJoinServerConfirmModalOpenRef,
      joinServerConfirmPreviewRef,
      joinServerConfirmBusyRef,
      confirmJoinServerFromModal,
      onJoinServerConfirmModalUpdate,
      isServerApplicationModalOpenRef,
      serverApplicationPayloadRef,
      serverApplicationBusyRef,
      onServerApplicationModalUpdate,
      confirmServerApplicationSubmittedFromModal,
      userSettingsModalCallbacks,
      memberPopoutChromeCallbacks,
    } as import('./buildAppLayoutAssemblyDeps').WireAppLayoutAssemblyInput),
  );

  const friendshipKnownComputed = computed(
    () =>
      echoSyncCapabilities.isMockDataMode ||
      workspace.socialGraphStatus.value === 'ready',
  );

  const expandedProfileHideOpenDmButtonComputed = computed(() => {
    const pid = expandedProfile.value?.id?.trim();
    if (!pid) return false;
    const selected = selectedDMUserId.value?.trim();
    return !!selected && selected === pid;
  });

  const dmSurfaceAdapter = useDmSurfaceAdapter({
    dmPartnerUser,
    activeGroupDM,
    activeDmThreadCallUi,
    isGroupDM: isGroupDMComputed,
    isInDMMode: isInDMModeComputed,
    isInDMChat: isInDmThreadOrIdleMainSurface,
    dmActiveTab: useComputedRefAlias(dmActiveTab),
    presenceByUserId: useComputedRefAlias(presenceByUserId),
    presenceMobileByUserId: useComputedOptionalRefAlias(presenceMobileByUserId),
    activeGroupCallMembers: activeGroupCallMembersVisible,
    openExpandedProfilePanelForUserId,
    openExtendedProfileModalForUserId,
    openGroupOverviewPanel: groupDmActions.openGroupOverviewPanel,
    openGroupSettingsFromHeader: groupDmActions.openGroupSettingsFromHeader,
  });

  const profileSurfaceAdapter = useProfileSurfaceAdapter({
    currentUserId: computed(() => currentUserComputed.value?.id),
    expandedProfile: useComputedRefAlias(expandedProfile),
    expandedProfileNote: useComputedRefAlias(expandedProfileNote),
    expandedProfileLoading: useComputedRefAlias(expandedProfileLoading),
    isExpandedProfileSidePanel: useComputedRefAlias(isExpandedProfileSidePanel),
    isExpandedProfileModalOpen: useComputedRefAlias(isExpandedProfileModalOpen),
    isExpandedProfileTargetBlocked: useComputedRefAlias(
      isExpandedProfileTargetBlockedComputed,
    ),
    friendshipKnown: useComputedRefAlias(friendshipKnownComputed),
    friendIds: computed(() => workspace.friendIds.value),
    friendIdsByUserId: computed(() => workspace.friendIdsByUserId.value),
    friendRequestsIncoming: computed(
      () => workspace.friendRequestsIncoming.value ?? [],
    ),
    friendRequestsOutgoing: computed(
      () => workspace.friendRequestsOutgoing.value ?? [],
    ),
    blockedUserIds: computed(() => workspace.blockedUserIds.value ?? []),
    guestFriendsLocked: useComputedRefAlias(guestFriendsLocked),
    presenceMobileByUserId: useComputedOptionalRefAlias(presenceMobileByUserId),
    hideOpenDmButton: useComputedRefAlias(
      expandedProfileHideOpenDmButtonComputed,
    ),
    onUpdateExpandedProfileNote: (note: string) => {
      const id =
        expandedProfileTargetUserId.value?.trim() ??
        expandedProfile.value?.id ??
        null;
      if (id) updateProfileNote(id, note);
    },
    onExpandedProfileModalUpdate,
    handleExpandedProfileOpenServer,
    handleExpandedProfileOpenProfile,
    expandDmProfileToFullModal,
    handleExpandedProfileOpenDM: (userId: string) => {
      handleExpandedProfileOpenDM(userId, selectDmUser, selectDMTab);
    },
    handleExpandedProfileSendFriendRequest: (userId: string) => {
      void sendFriendRequest(userId);
    },
    handleExpandedProfileCancelOutgoingFriendRequest,
    handleExpandedProfileAcceptIncomingFriendRequest,
    handleExpandedProfileDeclineIncomingFriendRequest,
    handleExpandedProfileRemoveFriend,
    handleProfileBlockUser,
    handleProfileUnblockUser,
    handleProfileReportUser,
  });

  const chatHeaderAdapter = useChatHeaderAdapter({
    dmSurface: dmSurfaceAdapter,
    profileSurface: profileSurfaceAdapter,
  });

  const { fetchMembersForServer } = createEchoServerMemberOrchestration({
    authSession,
    echoSession,
    selectedServerId: selectedServerIdRef,
  });

  watch(
    selectedServerIdRef,
    (sid) => {
      if (sid && sid !== 'echo') {
        void fetchMembersForServer(sid);
      }
    },
    { immediate: true },
  );

  return Object.assign(buildAppLayoutExpose(context), {
    dmSurfaceAdapter,
    profileSurfaceAdapter,
    chatHeaderAdapter,
  });
}
